// Code generated by protoc-gen-go. DO NOT EDIT.
// source: system.proto

package system

import (
	err "biostar/service/err"
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CameraFrequency int32

const (
	CameraFrequency_FREQ_NONE CameraFrequency = 0
	CameraFrequency_FREQ_50HZ CameraFrequency = 1
	CameraFrequency_FREQ_60HZ CameraFrequency = 2
)

var CameraFrequency_name = map[int32]string{
	0: "FREQ_NONE",
	1: "FREQ_50HZ",
	2: "FREQ_60HZ",
}

var CameraFrequency_value = map[string]int32{
	"FREQ_NONE": 0,
	"FREQ_50HZ": 1,
	"FREQ_60HZ": 2,
}

func (x CameraFrequency) String() string {
	return proto.EnumName(CameraFrequency_name, int32(x))
}

func (CameraFrequency) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_86a7260ebdc12f47, []int{0}
}

type SystemConfig struct {
	TimeZone             int32           `protobuf:"varint,1,opt,name=timeZone,proto3" json:"timeZone,omitempty"`
	SyncTime             bool            `protobuf:"varint,2,opt,name=syncTime,proto3" json:"syncTime,omitempty"`
	IsLocked             bool            `protobuf:"varint,3,opt,name=isLocked,proto3" json:"isLocked,omitempty"`
	UseInterphone        bool            `protobuf:"varint,4,opt,name=useInterphone,proto3" json:"useInterphone,omitempty"`
	OSDPKeyEncrypted     bool            `protobuf:"varint,5,opt,name=OSDPKeyEncrypted,proto3" json:"OSDPKeyEncrypted,omitempty"`
	UseJobCode           bool            `protobuf:"varint,6,opt,name=useJobCode,proto3" json:"useJobCode,omitempty"`
	UseAlphanumericID    bool            `protobuf:"varint,7,opt,name=useAlphanumericID,proto3" json:"useAlphanumericID,omitempty"`
	CameraFrequency      CameraFrequency `protobuf:"varint,8,opt,name=cameraFrequency,proto3,enum=system.CameraFrequency" json:"cameraFrequency,omitempty"`
	UseSecureTamper      bool            `protobuf:"varint,9,opt,name=useSecureTamper,proto3" json:"useSecureTamper,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SystemConfig) Reset()         { *m = SystemConfig{} }
func (m *SystemConfig) String() string { return proto.CompactTextString(m) }
func (*SystemConfig) ProtoMessage()    {}
func (*SystemConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_86a7260ebdc12f47, []int{0}
}

func (m *SystemConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemConfig.Unmarshal(m, b)
}
func (m *SystemConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemConfig.Marshal(b, m, deterministic)
}
func (m *SystemConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemConfig.Merge(m, src)
}
func (m *SystemConfig) XXX_Size() int {
	return xxx_messageInfo_SystemConfig.Size(m)
}
func (m *SystemConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemConfig.DiscardUnknown(m)
}

var xxx_messageInfo_SystemConfig proto.InternalMessageInfo

func (m *SystemConfig) GetTimeZone() int32 {
	if m != nil {
		return m.TimeZone
	}
	return 0
}

func (m *SystemConfig) GetSyncTime() bool {
	if m != nil {
		return m.SyncTime
	}
	return false
}

func (m *SystemConfig) GetIsLocked() bool {
	if m != nil {
		return m.IsLocked
	}
	return false
}

func (m *SystemConfig) GetUseInterphone() bool {
	if m != nil {
		return m.UseInterphone
	}
	return false
}

func (m *SystemConfig) GetOSDPKeyEncrypted() bool {
	if m != nil {
		return m.OSDPKeyEncrypted
	}
	return false
}

func (m *SystemConfig) GetUseJobCode() bool {
	if m != nil {
		return m.UseJobCode
	}
	return false
}

func (m *SystemConfig) GetUseAlphanumericID() bool {
	if m != nil {
		return m.UseAlphanumericID
	}
	return false
}

func (m *SystemConfig) GetCameraFrequency() CameraFrequency {
	if m != nil {
		return m.CameraFrequency
	}
	return CameraFrequency_FREQ_NONE
}

func (m *SystemConfig) GetUseSecureTamper() bool {
	if m != nil {
		return m.UseSecureTamper
	}
	return false
}

type GetConfigRequest struct {
	DeviceID             uint32   `protobuf:"varint,1,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConfigRequest) Reset()         { *m = GetConfigRequest{} }
func (m *GetConfigRequest) String() string { return proto.CompactTextString(m) }
func (*GetConfigRequest) ProtoMessage()    {}
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_86a7260ebdc12f47, []int{1}
}

func (m *GetConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigRequest.Unmarshal(m, b)
}
func (m *GetConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigRequest.Marshal(b, m, deterministic)
}
func (m *GetConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigRequest.Merge(m, src)
}
func (m *GetConfigRequest) XXX_Size() int {
	return xxx_messageInfo_GetConfigRequest.Size(m)
}
func (m *GetConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigRequest proto.InternalMessageInfo

func (m *GetConfigRequest) GetDeviceID() uint32 {
	if m != nil {
		return m.DeviceID
	}
	return 0
}

type GetConfigResponse struct {
	Config               *SystemConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetConfigResponse) Reset()         { *m = GetConfigResponse{} }
func (m *GetConfigResponse) String() string { return proto.CompactTextString(m) }
func (*GetConfigResponse) ProtoMessage()    {}
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_86a7260ebdc12f47, []int{2}
}

func (m *GetConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigResponse.Unmarshal(m, b)
}
func (m *GetConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigResponse.Marshal(b, m, deterministic)
}
func (m *GetConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigResponse.Merge(m, src)
}
func (m *GetConfigResponse) XXX_Size() int {
	return xxx_messageInfo_GetConfigResponse.Size(m)
}
func (m *GetConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigResponse proto.InternalMessageInfo

func (m *GetConfigResponse) GetConfig() *SystemConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

type SetConfigRequest struct {
	DeviceID             uint32        `protobuf:"varint,1,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	Config               *SystemConfig `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SetConfigRequest) Reset()         { *m = SetConfigRequest{} }
func (m *SetConfigRequest) String() string { return proto.CompactTextString(m) }
func (*SetConfigRequest) ProtoMessage()    {}
func (*SetConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_86a7260ebdc12f47, []int{3}
}

func (m *SetConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetConfigRequest.Unmarshal(m, b)
}
func (m *SetConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetConfigRequest.Marshal(b, m, deterministic)
}
func (m *SetConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetConfigRequest.Merge(m, src)
}
func (m *SetConfigRequest) XXX_Size() int {
	return xxx_messageInfo_SetConfigRequest.Size(m)
}
func (m *SetConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetConfigRequest proto.InternalMessageInfo

func (m *SetConfigRequest) GetDeviceID() uint32 {
	if m != nil {
		return m.DeviceID
	}
	return 0
}

func (m *SetConfigRequest) GetConfig() *SystemConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

type SetConfigResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetConfigResponse) Reset()         { *m = SetConfigResponse{} }
func (m *SetConfigResponse) String() string { return proto.CompactTextString(m) }
func (*SetConfigResponse) ProtoMessage()    {}
func (*SetConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_86a7260ebdc12f47, []int{4}
}

func (m *SetConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetConfigResponse.Unmarshal(m, b)
}
func (m *SetConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetConfigResponse.Marshal(b, m, deterministic)
}
func (m *SetConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetConfigResponse.Merge(m, src)
}
func (m *SetConfigResponse) XXX_Size() int {
	return xxx_messageInfo_SetConfigResponse.Size(m)
}
func (m *SetConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetConfigResponse proto.InternalMessageInfo

type SetConfigMultiRequest struct {
	DeviceIDs            []uint32      `protobuf:"varint,1,rep,packed,name=deviceIDs,proto3" json:"deviceIDs,omitempty"`
	Config               *SystemConfig `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SetConfigMultiRequest) Reset()         { *m = SetConfigMultiRequest{} }
func (m *SetConfigMultiRequest) String() string { return proto.CompactTextString(m) }
func (*SetConfigMultiRequest) ProtoMessage()    {}
func (*SetConfigMultiRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_86a7260ebdc12f47, []int{5}
}

func (m *SetConfigMultiRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetConfigMultiRequest.Unmarshal(m, b)
}
func (m *SetConfigMultiRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetConfigMultiRequest.Marshal(b, m, deterministic)
}
func (m *SetConfigMultiRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetConfigMultiRequest.Merge(m, src)
}
func (m *SetConfigMultiRequest) XXX_Size() int {
	return xxx_messageInfo_SetConfigMultiRequest.Size(m)
}
func (m *SetConfigMultiRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetConfigMultiRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetConfigMultiRequest proto.InternalMessageInfo

func (m *SetConfigMultiRequest) GetDeviceIDs() []uint32 {
	if m != nil {
		return m.DeviceIDs
	}
	return nil
}

func (m *SetConfigMultiRequest) GetConfig() *SystemConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

type SetConfigMultiResponse struct {
	DeviceErrors         []*err.ErrorResponse `protobuf:"bytes,1,rep,name=deviceErrors,proto3" json:"deviceErrors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SetConfigMultiResponse) Reset()         { *m = SetConfigMultiResponse{} }
func (m *SetConfigMultiResponse) String() string { return proto.CompactTextString(m) }
func (*SetConfigMultiResponse) ProtoMessage()    {}
func (*SetConfigMultiResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_86a7260ebdc12f47, []int{6}
}

func (m *SetConfigMultiResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetConfigMultiResponse.Unmarshal(m, b)
}
func (m *SetConfigMultiResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetConfigMultiResponse.Marshal(b, m, deterministic)
}
func (m *SetConfigMultiResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetConfigMultiResponse.Merge(m, src)
}
func (m *SetConfigMultiResponse) XXX_Size() int {
	return xxx_messageInfo_SetConfigMultiResponse.Size(m)
}
func (m *SetConfigMultiResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetConfigMultiResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetConfigMultiResponse proto.InternalMessageInfo

func (m *SetConfigMultiResponse) GetDeviceErrors() []*err.ErrorResponse {
	if m != nil {
		return m.DeviceErrors
	}
	return nil
}

func init() {
	proto.RegisterEnum("system.CameraFrequency", CameraFrequency_name, CameraFrequency_value)
	proto.RegisterType((*SystemConfig)(nil), "system.SystemConfig")
	proto.RegisterType((*GetConfigRequest)(nil), "system.GetConfigRequest")
	proto.RegisterType((*GetConfigResponse)(nil), "system.GetConfigResponse")
	proto.RegisterType((*SetConfigRequest)(nil), "system.SetConfigRequest")
	proto.RegisterType((*SetConfigResponse)(nil), "system.SetConfigResponse")
	proto.RegisterType((*SetConfigMultiRequest)(nil), "system.SetConfigMultiRequest")
	proto.RegisterType((*SetConfigMultiResponse)(nil), "system.SetConfigMultiResponse")
}

func init() { proto.RegisterFile("system.proto", fileDescriptor_86a7260ebdc12f47) }

var fileDescriptor_86a7260ebdc12f47 = []byte{
	// 519 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xdd, 0x6e, 0xd3, 0x30,
	0x14, 0x26, 0x1d, 0x2b, 0xcb, 0x59, 0xbb, 0xb6, 0x06, 0x86, 0x57, 0xc1, 0x54, 0x55, 0x5c, 0x54,
	0x13, 0xca, 0x50, 0xd1, 0x76, 0x89, 0x56, 0xda, 0x0e, 0xca, 0xcf, 0x5a, 0x92, 0x5d, 0x55, 0x48,
	0x28, 0x75, 0x0f, 0x2c, 0xda, 0x12, 0x07, 0x3b, 0x41, 0xca, 0xc3, 0xf2, 0x0c, 0xbc, 0x02, 0x8a,
	0xf3, 0x43, 0x9a, 0x30, 0x89, 0x5d, 0x7e, 0x3f, 0x3e, 0x9f, 0xfd, 0x9d, 0x28, 0xd0, 0x90, 0x91,
	0x0c, 0xd0, 0x35, 0x7c, 0xc1, 0x03, 0x4e, 0xea, 0x09, 0xea, 0xea, 0x28, 0x44, 0x42, 0xf5, 0x7f,
	0xd7, 0xa0, 0x61, 0x29, 0x76, 0xcc, 0xbd, 0x6f, 0xce, 0x77, 0xd2, 0x85, 0x9d, 0xc0, 0x71, 0x71,
	0xc9, 0x3d, 0xa4, 0x5a, 0x4f, 0x1b, 0x6c, 0x9b, 0x39, 0x8e, 0x35, 0x19, 0x79, 0xec, 0xd2, 0x71,
	0x91, 0xd6, 0x7a, 0xda, 0x60, 0xc7, 0xcc, 0x71, 0xac, 0x39, 0xf2, 0x23, 0x67, 0xd7, 0xb8, 0xa6,
	0x5b, 0x89, 0x96, 0x61, 0xf2, 0x1c, 0x9a, 0xa1, 0xc4, 0x99, 0x17, 0xa0, 0xf0, 0xaf, 0xe2, 0xc1,
	0xf7, 0x95, 0x61, 0x93, 0x24, 0x47, 0xd0, 0x9e, 0x5b, 0x93, 0xc5, 0x07, 0x8c, 0xa6, 0x1e, 0x13,
	0x91, 0x1f, 0xe0, 0x9a, 0x6e, 0x2b, 0x63, 0x85, 0x27, 0x87, 0x00, 0xa1, 0xc4, 0xf7, 0x7c, 0x35,
	0xe6, 0x6b, 0xa4, 0x75, 0xe5, 0x2a, 0x30, 0xe4, 0x05, 0x74, 0x42, 0x89, 0xa3, 0x1b, 0xff, 0xca,
	0xf6, 0x42, 0x17, 0x85, 0xc3, 0x66, 0x13, 0xfa, 0x40, 0xd9, 0xaa, 0x02, 0x19, 0x41, 0x8b, 0xd9,
	0x2e, 0x0a, 0xfb, 0x5c, 0xe0, 0x8f, 0x10, 0x3d, 0x16, 0xd1, 0x9d, 0x9e, 0x36, 0xd8, 0x1b, 0x3e,
	0x31, 0xd2, 0xfe, 0xc6, 0x9b, 0xb2, 0x59, 0xf6, 0x93, 0x01, 0xb4, 0x42, 0x89, 0x16, 0xb2, 0x50,
	0xe0, 0xa5, 0xed, 0xfa, 0x28, 0xa8, 0xae, 0xe2, 0xca, 0x74, 0xdf, 0x80, 0xf6, 0x5b, 0x0c, 0x92,
	0xb6, 0xcd, 0xf8, 0xb8, 0x0c, 0xe2, 0xf2, 0xd6, 0xf8, 0xd3, 0x61, 0x38, 0x9b, 0xa8, 0xd2, 0x9b,
	0x66, 0x8e, 0xfb, 0x23, 0xe8, 0x14, 0xfc, 0xd2, 0xe7, 0x9e, 0x8c, 0xdf, 0x57, 0x67, 0x8a, 0x51,
	0xf6, 0xdd, 0xe1, 0xa3, 0xec, 0xa2, 0xc5, 0x5d, 0x9a, 0xa9, 0xa7, 0xff, 0x05, 0xda, 0xd6, 0x1d,
	0x22, 0x0b, 0xd3, 0x6b, 0xff, 0x31, 0xfd, 0x21, 0x74, 0xac, 0xf2, 0x05, 0xfb, 0x0c, 0x1e, 0xe7,
	0xe4, 0xa7, 0xf0, 0x26, 0x70, 0xb2, 0xdc, 0xa7, 0xa0, 0x67, 0x39, 0x92, 0x6a, 0xbd, 0xad, 0x41,
	0xd3, 0xfc, 0x4b, 0xdc, 0x31, 0x79, 0x01, 0xfb, 0xe5, 0x90, 0xb4, 0x9f, 0x53, 0x68, 0x24, 0x43,
	0xa7, 0x42, 0x70, 0x91, 0x04, 0xed, 0x0e, 0x89, 0x11, 0x7f, 0xf8, 0x8a, 0xca, 0x9c, 0xe6, 0x86,
	0xef, 0xe8, 0x35, 0xb4, 0x4a, 0xab, 0x26, 0x4d, 0xd0, 0xcf, 0xcd, 0xe9, 0xe7, 0xaf, 0x17, 0xf3,
	0x8b, 0x69, 0xfb, 0x5e, 0x0e, 0x4f, 0x5e, 0xbe, 0x5b, 0xb6, 0xb5, 0x1c, 0x9e, 0xc6, 0xb0, 0x36,
	0xfc, 0xa5, 0x41, 0x3d, 0xb9, 0x2a, 0x39, 0x03, 0x3d, 0xdf, 0x1b, 0xa1, 0xd9, 0x3b, 0xca, 0xab,
	0xef, 0x1e, 0xfc, 0x43, 0x49, 0x1f, 0x71, 0x06, 0xba, 0x55, 0x9d, 0x60, 0xdd, 0x3a, 0xa1, 0xb2,
	0x05, 0x32, 0x87, 0xbd, 0xcd, 0x82, 0xc8, 0xb3, 0x8a, 0xb9, 0xb8, 0x9d, 0xee, 0xe1, 0x6d, 0x72,
	0x32, 0xf0, 0xcd, 0x09, 0x1c, 0x30, 0xee, 0x1a, 0x32, 0xf4, 0x05, 0xba, 0xb6, 0xe3, 0x31, 0x43,
	0xae, 0xaf, 0xd3, 0x33, 0x0b, 0x6d, 0xb9, 0xbf, 0x72, 0xb8, 0x0c, 0x6c, 0x71, 0x2c, 0x51, 0xc4,
	0xad, 0x1e, 0x27, 0xca, 0xaa, 0xae, 0x7e, 0x36, 0xaf, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0xb4,
	0x9b, 0x05, 0x88, 0x8f, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SystemClient is the client API for System service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SystemClient interface {
	GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error)
	SetConfig(ctx context.Context, in *SetConfigRequest, opts ...grpc.CallOption) (*SetConfigResponse, error)
	SetConfigMulti(ctx context.Context, in *SetConfigMultiRequest, opts ...grpc.CallOption) (*SetConfigMultiResponse, error)
}

type systemClient struct {
	cc *grpc.ClientConn
}

func NewSystemClient(cc *grpc.ClientConn) SystemClient {
	return &systemClient{cc}
}

func (c *systemClient) GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error) {
	out := new(GetConfigResponse)
	err := c.cc.Invoke(ctx, "/system.System/GetConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemClient) SetConfig(ctx context.Context, in *SetConfigRequest, opts ...grpc.CallOption) (*SetConfigResponse, error) {
	out := new(SetConfigResponse)
	err := c.cc.Invoke(ctx, "/system.System/SetConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemClient) SetConfigMulti(ctx context.Context, in *SetConfigMultiRequest, opts ...grpc.CallOption) (*SetConfigMultiResponse, error) {
	out := new(SetConfigMultiResponse)
	err := c.cc.Invoke(ctx, "/system.System/SetConfigMulti", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SystemServer is the server API for System service.
type SystemServer interface {
	GetConfig(context.Context, *GetConfigRequest) (*GetConfigResponse, error)
	SetConfig(context.Context, *SetConfigRequest) (*SetConfigResponse, error)
	SetConfigMulti(context.Context, *SetConfigMultiRequest) (*SetConfigMultiResponse, error)
}

func RegisterSystemServer(s *grpc.Server, srv SystemServer) {
	s.RegisterService(&_System_serviceDesc, srv)
}

func _System_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/system.System/GetConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServer).GetConfig(ctx, req.(*GetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _System_SetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServer).SetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/system.System/SetConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServer).SetConfig(ctx, req.(*SetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _System_SetConfigMulti_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetConfigMultiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServer).SetConfigMulti(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/system.System/SetConfigMulti",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServer).SetConfigMulti(ctx, req.(*SetConfigMultiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _System_serviceDesc = grpc.ServiceDesc{
	ServiceName: "system.System",
	HandlerType: (*SystemServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConfig",
			Handler:    _System_GetConfig_Handler,
		},
		{
			MethodName: "SetConfig",
			Handler:    _System_SetConfig_Handler,
		},
		{
			MethodName: "SetConfigMulti",
			Handler:    _System_SetConfigMulti_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "system.proto",
}
