// Code generated by protoc-gen-go. DO NOT EDIT.
// source: face.proto

package face

import (
	err "biostar/service/err"
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FaceSecurityLevel int32

const (
	FaceSecurityLevel_BS2_FACE_SECURITY_NORMAL      FaceSecurityLevel = 0
	FaceSecurityLevel_BS2_FACE_SECURITY_SECURE      FaceSecurityLevel = 1
	FaceSecurityLevel_BS2_FACE_SECURITY_MORE_SECURE FaceSecurityLevel = 2
	FaceSecurityLevel_BS2_FACE_SECURITY_DEFAULT     FaceSecurityLevel = 0
)

var FaceSecurityLevel_name = map[int32]string{
	0: "BS2_FACE_SECURITY_NORMAL",
	1: "BS2_FACE_SECURITY_SECURE",
	2: "BS2_FACE_SECURITY_MORE_SECURE",
	// Duplicate value: 0: "BS2_FACE_SECURITY_DEFAULT",
}

var FaceSecurityLevel_value = map[string]int32{
	"BS2_FACE_SECURITY_NORMAL":      0,
	"BS2_FACE_SECURITY_SECURE":      1,
	"BS2_FACE_SECURITY_MORE_SECURE": 2,
	"BS2_FACE_SECURITY_DEFAULT":     0,
}

func (x FaceSecurityLevel) String() string {
	return proto.EnumName(FaceSecurityLevel_name, int32(x))
}

func (FaceSecurityLevel) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_543a5193e84d47c5, []int{0}
}

type FaceEnrollThreshold int32

const (
	FaceEnrollThreshold_BS2_FACE_ENROLL_THRESHOLD_0       FaceEnrollThreshold = 0
	FaceEnrollThreshold_BS2_FACE_ENROLL_THRESHOLD_1       FaceEnrollThreshold = 1
	FaceEnrollThreshold_BS2_FACE_ENROLL_THRESHOLD_2       FaceEnrollThreshold = 2
	FaceEnrollThreshold_BS2_FACE_ENROLL_THRESHOLD_3       FaceEnrollThreshold = 3
	FaceEnrollThreshold_BS2_FACE_ENROLL_THRESHOLD_4       FaceEnrollThreshold = 4
	FaceEnrollThreshold_BS2_FACE_ENROLL_THRESHOLD_5       FaceEnrollThreshold = 5
	FaceEnrollThreshold_BS2_FACE_ENROLL_THRESHOLD_6       FaceEnrollThreshold = 6
	FaceEnrollThreshold_BS2_FACE_ENROLL_THRESHOLD_7       FaceEnrollThreshold = 7
	FaceEnrollThreshold_BS2_FACE_ENROLL_THRESHOLD_8       FaceEnrollThreshold = 8
	FaceEnrollThreshold_BS2_FACE_ENROLL_THRESHOLD_9       FaceEnrollThreshold = 9
	FaceEnrollThreshold_BS2_FACE_ENROLL_THRESHOLD_DEFAULT FaceEnrollThreshold = 4
)

var FaceEnrollThreshold_name = map[int32]string{
	0: "BS2_FACE_ENROLL_THRESHOLD_0",
	1: "BS2_FACE_ENROLL_THRESHOLD_1",
	2: "BS2_FACE_ENROLL_THRESHOLD_2",
	3: "BS2_FACE_ENROLL_THRESHOLD_3",
	4: "BS2_FACE_ENROLL_THRESHOLD_4",
	5: "BS2_FACE_ENROLL_THRESHOLD_5",
	6: "BS2_FACE_ENROLL_THRESHOLD_6",
	7: "BS2_FACE_ENROLL_THRESHOLD_7",
	8: "BS2_FACE_ENROLL_THRESHOLD_8",
	9: "BS2_FACE_ENROLL_THRESHOLD_9",
	// Duplicate value: 4: "BS2_FACE_ENROLL_THRESHOLD_DEFAULT",
}

var FaceEnrollThreshold_value = map[string]int32{
	"BS2_FACE_ENROLL_THRESHOLD_0":       0,
	"BS2_FACE_ENROLL_THRESHOLD_1":       1,
	"BS2_FACE_ENROLL_THRESHOLD_2":       2,
	"BS2_FACE_ENROLL_THRESHOLD_3":       3,
	"BS2_FACE_ENROLL_THRESHOLD_4":       4,
	"BS2_FACE_ENROLL_THRESHOLD_5":       5,
	"BS2_FACE_ENROLL_THRESHOLD_6":       6,
	"BS2_FACE_ENROLL_THRESHOLD_7":       7,
	"BS2_FACE_ENROLL_THRESHOLD_8":       8,
	"BS2_FACE_ENROLL_THRESHOLD_9":       9,
	"BS2_FACE_ENROLL_THRESHOLD_DEFAULT": 4,
}

func (x FaceEnrollThreshold) String() string {
	return proto.EnumName(FaceEnrollThreshold_name, int32(x))
}

func (FaceEnrollThreshold) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_543a5193e84d47c5, []int{1}
}

type FaceLightCondition int32

const (
	FaceLightCondition_BS2_FACE_LIGHT_CONDITION_INDOOR  FaceLightCondition = 0
	FaceLightCondition_BS2_FACE_LIGHT_CONDITION_OUTDOOR FaceLightCondition = 1
	FaceLightCondition_BS2_FACE_LIGHT_CONDITION_AUTO    FaceLightCondition = 2
	FaceLightCondition_BS2_FACE_LIGHT_CONDITION_DARK    FaceLightCondition = 3
	FaceLightCondition_BS2_FACE_LIGHT_CONDITION_DEFAULT FaceLightCondition = 0
)

var FaceLightCondition_name = map[int32]string{
	0: "BS2_FACE_LIGHT_CONDITION_INDOOR",
	1: "BS2_FACE_LIGHT_CONDITION_OUTDOOR",
	2: "BS2_FACE_LIGHT_CONDITION_AUTO",
	3: "BS2_FACE_LIGHT_CONDITION_DARK",
	// Duplicate value: 0: "BS2_FACE_LIGHT_CONDITION_DEFAULT",
}

var FaceLightCondition_value = map[string]int32{
	"BS2_FACE_LIGHT_CONDITION_INDOOR":  0,
	"BS2_FACE_LIGHT_CONDITION_OUTDOOR": 1,
	"BS2_FACE_LIGHT_CONDITION_AUTO":    2,
	"BS2_FACE_LIGHT_CONDITION_DARK":    3,
	"BS2_FACE_LIGHT_CONDITION_DEFAULT": 0,
}

func (x FaceLightCondition) String() string {
	return proto.EnumName(FaceLightCondition_name, int32(x))
}

func (FaceLightCondition) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_543a5193e84d47c5, []int{2}
}

type FaceDetectSensitivity int32

const (
	FaceDetectSensitivity_BS2_FACE_DETECT_SENSITIVITY_OFF     FaceDetectSensitivity = 0
	FaceDetectSensitivity_BS2_FACE_DETECT_SENSITIVITY_LOW     FaceDetectSensitivity = 1
	FaceDetectSensitivity_BS2_FACE_DETECT_SENSITIVITY_MIDDLE  FaceDetectSensitivity = 2
	FaceDetectSensitivity_BS2_FACE_DETECT_SENSITIVITY_HIGH    FaceDetectSensitivity = 3
	FaceDetectSensitivity_BS2_FACE_DETECT_SENSITIVITY_DEFAULT FaceDetectSensitivity = 2
)

var FaceDetectSensitivity_name = map[int32]string{
	0: "BS2_FACE_DETECT_SENSITIVITY_OFF",
	1: "BS2_FACE_DETECT_SENSITIVITY_LOW",
	2: "BS2_FACE_DETECT_SENSITIVITY_MIDDLE",
	3: "BS2_FACE_DETECT_SENSITIVITY_HIGH",
	// Duplicate value: 2: "BS2_FACE_DETECT_SENSITIVITY_DEFAULT",
}

var FaceDetectSensitivity_value = map[string]int32{
	"BS2_FACE_DETECT_SENSITIVITY_OFF":     0,
	"BS2_FACE_DETECT_SENSITIVITY_LOW":     1,
	"BS2_FACE_DETECT_SENSITIVITY_MIDDLE":  2,
	"BS2_FACE_DETECT_SENSITIVITY_HIGH":    3,
	"BS2_FACE_DETECT_SENSITIVITY_DEFAULT": 2,
}

func (x FaceDetectSensitivity) String() string {
	return proto.EnumName(FaceDetectSensitivity_name, int32(x))
}

func (FaceDetectSensitivity) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_543a5193e84d47c5, []int{3}
}

type FaceLFDLevel int32

const (
	FaceLFDLevel_BS2_FACE_LFD_LEVEL_OFF     FaceLFDLevel = 0
	FaceLFDLevel_BS2_FACE_LFD_LEVEL_LOW     FaceLFDLevel = 1
	FaceLFDLevel_BS2_FACE_LFD_LEVEL_MIDDLE  FaceLFDLevel = 2
	FaceLFDLevel_BS2_FACE_LFD_LEVEL_HIGH    FaceLFDLevel = 3
	FaceLFDLevel_BS2_FACE_LFD_LEVEL_DEFAULT FaceLFDLevel = 0
)

var FaceLFDLevel_name = map[int32]string{
	0: "BS2_FACE_LFD_LEVEL_OFF",
	1: "BS2_FACE_LFD_LEVEL_LOW",
	2: "BS2_FACE_LFD_LEVEL_MIDDLE",
	3: "BS2_FACE_LFD_LEVEL_HIGH",
	// Duplicate value: 0: "BS2_FACE_LFD_LEVEL_DEFAULT",
}

var FaceLFDLevel_value = map[string]int32{
	"BS2_FACE_LFD_LEVEL_OFF":     0,
	"BS2_FACE_LFD_LEVEL_LOW":     1,
	"BS2_FACE_LFD_LEVEL_MIDDLE":  2,
	"BS2_FACE_LFD_LEVEL_HIGH":    3,
	"BS2_FACE_LFD_LEVEL_DEFAULT": 0,
}

func (x FaceLFDLevel) String() string {
	return proto.EnumName(FaceLFDLevel_name, int32(x))
}

func (FaceLFDLevel) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_543a5193e84d47c5, []int{4}
}

type FacePreviewOption int32

const (
	FacePreviewOption_BS2_FACE_PREVIEW_NONE    FacePreviewOption = 0
	FacePreviewOption_BS2_FACE_PREVIEW_HALF    FacePreviewOption = 1
	FacePreviewOption_BS2_FACE_PREVIEW_FULL    FacePreviewOption = 2
	FacePreviewOption_BS2_FACE_PREVIEW_DEFAULT FacePreviewOption = 1
)

var FacePreviewOption_name = map[int32]string{
	0: "BS2_FACE_PREVIEW_NONE",
	1: "BS2_FACE_PREVIEW_HALF",
	2: "BS2_FACE_PREVIEW_FULL",
	// Duplicate value: 1: "BS2_FACE_PREVIEW_DEFAULT",
}

var FacePreviewOption_value = map[string]int32{
	"BS2_FACE_PREVIEW_NONE":    0,
	"BS2_FACE_PREVIEW_HALF":    1,
	"BS2_FACE_PREVIEW_FULL":    2,
	"BS2_FACE_PREVIEW_DEFAULT": 1,
}

func (x FacePreviewOption) String() string {
	return proto.EnumName(FacePreviewOption_name, int32(x))
}

func (FacePreviewOption) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_543a5193e84d47c5, []int{5}
}

type FaceData struct {
	Index                int32    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Flag                 uint32   `protobuf:"varint,2,opt,name=flag,proto3" json:"flag,omitempty"`
	Templates            [][]byte `protobuf:"bytes,3,rep,name=templates,proto3" json:"templates,omitempty"`
	ImageData            []byte   `protobuf:"bytes,5,opt,name=imageData,proto3" json:"imageData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FaceData) Reset()         { *m = FaceData{} }
func (m *FaceData) String() string { return proto.CompactTextString(m) }
func (*FaceData) ProtoMessage()    {}
func (*FaceData) Descriptor() ([]byte, []int) {
	return fileDescriptor_543a5193e84d47c5, []int{0}
}

func (m *FaceData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FaceData.Unmarshal(m, b)
}
func (m *FaceData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FaceData.Marshal(b, m, deterministic)
}
func (m *FaceData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FaceData.Merge(m, src)
}
func (m *FaceData) XXX_Size() int {
	return xxx_messageInfo_FaceData.Size(m)
}
func (m *FaceData) XXX_DiscardUnknown() {
	xxx_messageInfo_FaceData.DiscardUnknown(m)
}

var xxx_messageInfo_FaceData proto.InternalMessageInfo

func (m *FaceData) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *FaceData) GetFlag() uint32 {
	if m != nil {
		return m.Flag
	}
	return 0
}

func (m *FaceData) GetTemplates() [][]byte {
	if m != nil {
		return m.Templates
	}
	return nil
}

func (m *FaceData) GetImageData() []byte {
	if m != nil {
		return m.ImageData
	}
	return nil
}

type ScanRequest struct {
	DeviceID             uint32              `protobuf:"varint,1,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	EnrollThreshold      FaceEnrollThreshold `protobuf:"varint,2,opt,name=enrollThreshold,proto3,enum=face.FaceEnrollThreshold" json:"enrollThreshold,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ScanRequest) Reset()         { *m = ScanRequest{} }
func (m *ScanRequest) String() string { return proto.CompactTextString(m) }
func (*ScanRequest) ProtoMessage()    {}
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_543a5193e84d47c5, []int{1}
}

func (m *ScanRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScanRequest.Unmarshal(m, b)
}
func (m *ScanRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScanRequest.Marshal(b, m, deterministic)
}
func (m *ScanRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScanRequest.Merge(m, src)
}
func (m *ScanRequest) XXX_Size() int {
	return xxx_messageInfo_ScanRequest.Size(m)
}
func (m *ScanRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ScanRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ScanRequest proto.InternalMessageInfo

func (m *ScanRequest) GetDeviceID() uint32 {
	if m != nil {
		return m.DeviceID
	}
	return 0
}

func (m *ScanRequest) GetEnrollThreshold() FaceEnrollThreshold {
	if m != nil {
		return m.EnrollThreshold
	}
	return FaceEnrollThreshold_BS2_FACE_ENROLL_THRESHOLD_0
}

type ScanResponse struct {
	FaceData             *FaceData `protobuf:"bytes,2,opt,name=faceData,proto3" json:"faceData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ScanResponse) Reset()         { *m = ScanResponse{} }
func (m *ScanResponse) String() string { return proto.CompactTextString(m) }
func (*ScanResponse) ProtoMessage()    {}
func (*ScanResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_543a5193e84d47c5, []int{2}
}

func (m *ScanResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScanResponse.Unmarshal(m, b)
}
func (m *ScanResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScanResponse.Marshal(b, m, deterministic)
}
func (m *ScanResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScanResponse.Merge(m, src)
}
func (m *ScanResponse) XXX_Size() int {
	return xxx_messageInfo_ScanResponse.Size(m)
}
func (m *ScanResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ScanResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ScanResponse proto.InternalMessageInfo

func (m *ScanResponse) GetFaceData() *FaceData {
	if m != nil {
		return m.FaceData
	}
	return nil
}

type AuthGroup struct {
	ID                   uint32   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthGroup) Reset()         { *m = AuthGroup{} }
func (m *AuthGroup) String() string { return proto.CompactTextString(m) }
func (*AuthGroup) ProtoMessage()    {}
func (*AuthGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_543a5193e84d47c5, []int{3}
}

func (m *AuthGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthGroup.Unmarshal(m, b)
}
func (m *AuthGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthGroup.Marshal(b, m, deterministic)
}
func (m *AuthGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthGroup.Merge(m, src)
}
func (m *AuthGroup) XXX_Size() int {
	return xxx_messageInfo_AuthGroup.Size(m)
}
func (m *AuthGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthGroup.DiscardUnknown(m)
}

var xxx_messageInfo_AuthGroup proto.InternalMessageInfo

func (m *AuthGroup) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *AuthGroup) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetAuthGroupRequest struct {
	DeviceID             uint32   `protobuf:"varint,1,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAuthGroupRequest) Reset()         { *m = GetAuthGroupRequest{} }
func (m *GetAuthGroupRequest) String() string { return proto.CompactTextString(m) }
func (*GetAuthGroupRequest) ProtoMessage()    {}
func (*GetAuthGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_543a5193e84d47c5, []int{4}
}

func (m *GetAuthGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAuthGroupRequest.Unmarshal(m, b)
}
func (m *GetAuthGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAuthGroupRequest.Marshal(b, m, deterministic)
}
func (m *GetAuthGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAuthGroupRequest.Merge(m, src)
}
func (m *GetAuthGroupRequest) XXX_Size() int {
	return xxx_messageInfo_GetAuthGroupRequest.Size(m)
}
func (m *GetAuthGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAuthGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAuthGroupRequest proto.InternalMessageInfo

func (m *GetAuthGroupRequest) GetDeviceID() uint32 {
	if m != nil {
		return m.DeviceID
	}
	return 0
}

type GetAuthGroupResponse struct {
	AuthGroups           []*AuthGroup `protobuf:"bytes,1,rep,name=authGroups,proto3" json:"authGroups,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetAuthGroupResponse) Reset()         { *m = GetAuthGroupResponse{} }
func (m *GetAuthGroupResponse) String() string { return proto.CompactTextString(m) }
func (*GetAuthGroupResponse) ProtoMessage()    {}
func (*GetAuthGroupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_543a5193e84d47c5, []int{5}
}

func (m *GetAuthGroupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAuthGroupResponse.Unmarshal(m, b)
}
func (m *GetAuthGroupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAuthGroupResponse.Marshal(b, m, deterministic)
}
func (m *GetAuthGroupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAuthGroupResponse.Merge(m, src)
}
func (m *GetAuthGroupResponse) XXX_Size() int {
	return xxx_messageInfo_GetAuthGroupResponse.Size(m)
}
func (m *GetAuthGroupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAuthGroupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAuthGroupResponse proto.InternalMessageInfo

func (m *GetAuthGroupResponse) GetAuthGroups() []*AuthGroup {
	if m != nil {
		return m.AuthGroups
	}
	return nil
}

type AddAuthGroupRequest struct {
	DeviceID             uint32       `protobuf:"varint,1,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	AuthGroups           []*AuthGroup `protobuf:"bytes,2,rep,name=authGroups,proto3" json:"authGroups,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AddAuthGroupRequest) Reset()         { *m = AddAuthGroupRequest{} }
func (m *AddAuthGroupRequest) String() string { return proto.CompactTextString(m) }
func (*AddAuthGroupRequest) ProtoMessage()    {}
func (*AddAuthGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_543a5193e84d47c5, []int{6}
}

func (m *AddAuthGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddAuthGroupRequest.Unmarshal(m, b)
}
func (m *AddAuthGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddAuthGroupRequest.Marshal(b, m, deterministic)
}
func (m *AddAuthGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddAuthGroupRequest.Merge(m, src)
}
func (m *AddAuthGroupRequest) XXX_Size() int {
	return xxx_messageInfo_AddAuthGroupRequest.Size(m)
}
func (m *AddAuthGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddAuthGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddAuthGroupRequest proto.InternalMessageInfo

func (m *AddAuthGroupRequest) GetDeviceID() uint32 {
	if m != nil {
		return m.DeviceID
	}
	return 0
}

func (m *AddAuthGroupRequest) GetAuthGroups() []*AuthGroup {
	if m != nil {
		return m.AuthGroups
	}
	return nil
}

type AddAuthGroupResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddAuthGroupResponse) Reset()         { *m = AddAuthGroupResponse{} }
func (m *AddAuthGroupResponse) String() string { return proto.CompactTextString(m) }
func (*AddAuthGroupResponse) ProtoMessage()    {}
func (*AddAuthGroupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_543a5193e84d47c5, []int{7}
}

func (m *AddAuthGroupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddAuthGroupResponse.Unmarshal(m, b)
}
func (m *AddAuthGroupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddAuthGroupResponse.Marshal(b, m, deterministic)
}
func (m *AddAuthGroupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddAuthGroupResponse.Merge(m, src)
}
func (m *AddAuthGroupResponse) XXX_Size() int {
	return xxx_messageInfo_AddAuthGroupResponse.Size(m)
}
func (m *AddAuthGroupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddAuthGroupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddAuthGroupResponse proto.InternalMessageInfo

type AddAuthGroupMultiRequest struct {
	DeviceIDs            []uint32     `protobuf:"varint,1,rep,packed,name=deviceIDs,proto3" json:"deviceIDs,omitempty"`
	AuthGroups           []*AuthGroup `protobuf:"bytes,2,rep,name=authGroups,proto3" json:"authGroups,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AddAuthGroupMultiRequest) Reset()         { *m = AddAuthGroupMultiRequest{} }
func (m *AddAuthGroupMultiRequest) String() string { return proto.CompactTextString(m) }
func (*AddAuthGroupMultiRequest) ProtoMessage()    {}
func (*AddAuthGroupMultiRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_543a5193e84d47c5, []int{8}
}

func (m *AddAuthGroupMultiRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddAuthGroupMultiRequest.Unmarshal(m, b)
}
func (m *AddAuthGroupMultiRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddAuthGroupMultiRequest.Marshal(b, m, deterministic)
}
func (m *AddAuthGroupMultiRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddAuthGroupMultiRequest.Merge(m, src)
}
func (m *AddAuthGroupMultiRequest) XXX_Size() int {
	return xxx_messageInfo_AddAuthGroupMultiRequest.Size(m)
}
func (m *AddAuthGroupMultiRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddAuthGroupMultiRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddAuthGroupMultiRequest proto.InternalMessageInfo

func (m *AddAuthGroupMultiRequest) GetDeviceIDs() []uint32 {
	if m != nil {
		return m.DeviceIDs
	}
	return nil
}

func (m *AddAuthGroupMultiRequest) GetAuthGroups() []*AuthGroup {
	if m != nil {
		return m.AuthGroups
	}
	return nil
}

type AddAuthGroupMultiResponse struct {
	DeviceErrors         []*err.ErrorResponse `protobuf:"bytes,1,rep,name=deviceErrors,proto3" json:"deviceErrors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *AddAuthGroupMultiResponse) Reset()         { *m = AddAuthGroupMultiResponse{} }
func (m *AddAuthGroupMultiResponse) String() string { return proto.CompactTextString(m) }
func (*AddAuthGroupMultiResponse) ProtoMessage()    {}
func (*AddAuthGroupMultiResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_543a5193e84d47c5, []int{9}
}

func (m *AddAuthGroupMultiResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddAuthGroupMultiResponse.Unmarshal(m, b)
}
func (m *AddAuthGroupMultiResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddAuthGroupMultiResponse.Marshal(b, m, deterministic)
}
func (m *AddAuthGroupMultiResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddAuthGroupMultiResponse.Merge(m, src)
}
func (m *AddAuthGroupMultiResponse) XXX_Size() int {
	return xxx_messageInfo_AddAuthGroupMultiResponse.Size(m)
}
func (m *AddAuthGroupMultiResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddAuthGroupMultiResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddAuthGroupMultiResponse proto.InternalMessageInfo

func (m *AddAuthGroupMultiResponse) GetDeviceErrors() []*err.ErrorResponse {
	if m != nil {
		return m.DeviceErrors
	}
	return nil
}

type DeleteAuthGroupRequest struct {
	DeviceID             uint32   `protobuf:"varint,1,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	GroupIDs             []uint32 `protobuf:"varint,2,rep,packed,name=groupIDs,proto3" json:"groupIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAuthGroupRequest) Reset()         { *m = DeleteAuthGroupRequest{} }
func (m *DeleteAuthGroupRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAuthGroupRequest) ProtoMessage()    {}
func (*DeleteAuthGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_543a5193e84d47c5, []int{10}
}

func (m *DeleteAuthGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAuthGroupRequest.Unmarshal(m, b)
}
func (m *DeleteAuthGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAuthGroupRequest.Marshal(b, m, deterministic)
}
func (m *DeleteAuthGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAuthGroupRequest.Merge(m, src)
}
func (m *DeleteAuthGroupRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAuthGroupRequest.Size(m)
}
func (m *DeleteAuthGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAuthGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAuthGroupRequest proto.InternalMessageInfo

func (m *DeleteAuthGroupRequest) GetDeviceID() uint32 {
	if m != nil {
		return m.DeviceID
	}
	return 0
}

func (m *DeleteAuthGroupRequest) GetGroupIDs() []uint32 {
	if m != nil {
		return m.GroupIDs
	}
	return nil
}

type DeleteAuthGroupResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAuthGroupResponse) Reset()         { *m = DeleteAuthGroupResponse{} }
func (m *DeleteAuthGroupResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteAuthGroupResponse) ProtoMessage()    {}
func (*DeleteAuthGroupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_543a5193e84d47c5, []int{11}
}

func (m *DeleteAuthGroupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAuthGroupResponse.Unmarshal(m, b)
}
func (m *DeleteAuthGroupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAuthGroupResponse.Marshal(b, m, deterministic)
}
func (m *DeleteAuthGroupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAuthGroupResponse.Merge(m, src)
}
func (m *DeleteAuthGroupResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteAuthGroupResponse.Size(m)
}
func (m *DeleteAuthGroupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAuthGroupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAuthGroupResponse proto.InternalMessageInfo

type DeleteAuthGroupMultiRequest struct {
	DeviceIDs            []uint32 `protobuf:"varint,1,rep,packed,name=deviceIDs,proto3" json:"deviceIDs,omitempty"`
	GroupIDs             []uint32 `protobuf:"varint,2,rep,packed,name=groupIDs,proto3" json:"groupIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAuthGroupMultiRequest) Reset()         { *m = DeleteAuthGroupMultiRequest{} }
func (m *DeleteAuthGroupMultiRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAuthGroupMultiRequest) ProtoMessage()    {}
func (*DeleteAuthGroupMultiRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_543a5193e84d47c5, []int{12}
}

func (m *DeleteAuthGroupMultiRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAuthGroupMultiRequest.Unmarshal(m, b)
}
func (m *DeleteAuthGroupMultiRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAuthGroupMultiRequest.Marshal(b, m, deterministic)
}
func (m *DeleteAuthGroupMultiRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAuthGroupMultiRequest.Merge(m, src)
}
func (m *DeleteAuthGroupMultiRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAuthGroupMultiRequest.Size(m)
}
func (m *DeleteAuthGroupMultiRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAuthGroupMultiRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAuthGroupMultiRequest proto.InternalMessageInfo

func (m *DeleteAuthGroupMultiRequest) GetDeviceIDs() []uint32 {
	if m != nil {
		return m.DeviceIDs
	}
	return nil
}

func (m *DeleteAuthGroupMultiRequest) GetGroupIDs() []uint32 {
	if m != nil {
		return m.GroupIDs
	}
	return nil
}

type DeleteAuthGroupMultiResponse struct {
	DeviceErrors         []*err.ErrorResponse `protobuf:"bytes,1,rep,name=deviceErrors,proto3" json:"deviceErrors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DeleteAuthGroupMultiResponse) Reset()         { *m = DeleteAuthGroupMultiResponse{} }
func (m *DeleteAuthGroupMultiResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteAuthGroupMultiResponse) ProtoMessage()    {}
func (*DeleteAuthGroupMultiResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_543a5193e84d47c5, []int{13}
}

func (m *DeleteAuthGroupMultiResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAuthGroupMultiResponse.Unmarshal(m, b)
}
func (m *DeleteAuthGroupMultiResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAuthGroupMultiResponse.Marshal(b, m, deterministic)
}
func (m *DeleteAuthGroupMultiResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAuthGroupMultiResponse.Merge(m, src)
}
func (m *DeleteAuthGroupMultiResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteAuthGroupMultiResponse.Size(m)
}
func (m *DeleteAuthGroupMultiResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAuthGroupMultiResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAuthGroupMultiResponse proto.InternalMessageInfo

func (m *DeleteAuthGroupMultiResponse) GetDeviceErrors() []*err.ErrorResponse {
	if m != nil {
		return m.DeviceErrors
	}
	return nil
}

type DeleteAllAuthGroupRequest struct {
	DeviceID             uint32   `protobuf:"varint,1,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAllAuthGroupRequest) Reset()         { *m = DeleteAllAuthGroupRequest{} }
func (m *DeleteAllAuthGroupRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAllAuthGroupRequest) ProtoMessage()    {}
func (*DeleteAllAuthGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_543a5193e84d47c5, []int{14}
}

func (m *DeleteAllAuthGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAllAuthGroupRequest.Unmarshal(m, b)
}
func (m *DeleteAllAuthGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAllAuthGroupRequest.Marshal(b, m, deterministic)
}
func (m *DeleteAllAuthGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAllAuthGroupRequest.Merge(m, src)
}
func (m *DeleteAllAuthGroupRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAllAuthGroupRequest.Size(m)
}
func (m *DeleteAllAuthGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAllAuthGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAllAuthGroupRequest proto.InternalMessageInfo

func (m *DeleteAllAuthGroupRequest) GetDeviceID() uint32 {
	if m != nil {
		return m.DeviceID
	}
	return 0
}

type DeleteAllAuthGroupResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAllAuthGroupResponse) Reset()         { *m = DeleteAllAuthGroupResponse{} }
func (m *DeleteAllAuthGroupResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteAllAuthGroupResponse) ProtoMessage()    {}
func (*DeleteAllAuthGroupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_543a5193e84d47c5, []int{15}
}

func (m *DeleteAllAuthGroupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAllAuthGroupResponse.Unmarshal(m, b)
}
func (m *DeleteAllAuthGroupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAllAuthGroupResponse.Marshal(b, m, deterministic)
}
func (m *DeleteAllAuthGroupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAllAuthGroupResponse.Merge(m, src)
}
func (m *DeleteAllAuthGroupResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteAllAuthGroupResponse.Size(m)
}
func (m *DeleteAllAuthGroupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAllAuthGroupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAllAuthGroupResponse proto.InternalMessageInfo

type DeleteAllAuthGroupMultiRequest struct {
	DeviceIDs            []uint32 `protobuf:"varint,1,rep,packed,name=deviceIDs,proto3" json:"deviceIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAllAuthGroupMultiRequest) Reset()         { *m = DeleteAllAuthGroupMultiRequest{} }
func (m *DeleteAllAuthGroupMultiRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAllAuthGroupMultiRequest) ProtoMessage()    {}
func (*DeleteAllAuthGroupMultiRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_543a5193e84d47c5, []int{16}
}

func (m *DeleteAllAuthGroupMultiRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAllAuthGroupMultiRequest.Unmarshal(m, b)
}
func (m *DeleteAllAuthGroupMultiRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAllAuthGroupMultiRequest.Marshal(b, m, deterministic)
}
func (m *DeleteAllAuthGroupMultiRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAllAuthGroupMultiRequest.Merge(m, src)
}
func (m *DeleteAllAuthGroupMultiRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAllAuthGroupMultiRequest.Size(m)
}
func (m *DeleteAllAuthGroupMultiRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAllAuthGroupMultiRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAllAuthGroupMultiRequest proto.InternalMessageInfo

func (m *DeleteAllAuthGroupMultiRequest) GetDeviceIDs() []uint32 {
	if m != nil {
		return m.DeviceIDs
	}
	return nil
}

type DeleteAllAuthGroupMultiResponse struct {
	DeviceErrors         []*err.ErrorResponse `protobuf:"bytes,1,rep,name=deviceErrors,proto3" json:"deviceErrors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DeleteAllAuthGroupMultiResponse) Reset()         { *m = DeleteAllAuthGroupMultiResponse{} }
func (m *DeleteAllAuthGroupMultiResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteAllAuthGroupMultiResponse) ProtoMessage()    {}
func (*DeleteAllAuthGroupMultiResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_543a5193e84d47c5, []int{17}
}

func (m *DeleteAllAuthGroupMultiResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAllAuthGroupMultiResponse.Unmarshal(m, b)
}
func (m *DeleteAllAuthGroupMultiResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAllAuthGroupMultiResponse.Marshal(b, m, deterministic)
}
func (m *DeleteAllAuthGroupMultiResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAllAuthGroupMultiResponse.Merge(m, src)
}
func (m *DeleteAllAuthGroupMultiResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteAllAuthGroupMultiResponse.Size(m)
}
func (m *DeleteAllAuthGroupMultiResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAllAuthGroupMultiResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAllAuthGroupMultiResponse proto.InternalMessageInfo

func (m *DeleteAllAuthGroupMultiResponse) GetDeviceErrors() []*err.ErrorResponse {
	if m != nil {
		return m.DeviceErrors
	}
	return nil
}

type FaceConfig struct {
	SecurityLevel        FaceSecurityLevel     `protobuf:"varint,1,opt,name=securityLevel,proto3,enum=face.FaceSecurityLevel" json:"securityLevel,omitempty"`
	LightCondition       FaceLightCondition    `protobuf:"varint,2,opt,name=lightCondition,proto3,enum=face.FaceLightCondition" json:"lightCondition,omitempty"`
	EnrollThreshold      FaceEnrollThreshold   `protobuf:"varint,3,opt,name=enrollThreshold,proto3,enum=face.FaceEnrollThreshold" json:"enrollThreshold,omitempty"`
	DetectSensitivity    FaceDetectSensitivity `protobuf:"varint,4,opt,name=detectSensitivity,proto3,enum=face.FaceDetectSensitivity" json:"detectSensitivity,omitempty"`
	EnrollTimeout        uint32                `protobuf:"varint,5,opt,name=enrollTimeout,proto3" json:"enrollTimeout,omitempty"`
	LFDLevel             FaceLFDLevel          `protobuf:"varint,6,opt,name=LFDLevel,proto3,enum=face.FaceLFDLevel" json:"LFDLevel,omitempty"`
	QuickEnrollment      bool                  `protobuf:"varint,7,opt,name=quickEnrollment,proto3" json:"quickEnrollment,omitempty"`
	PreviewOption        FacePreviewOption     `protobuf:"varint,8,opt,name=previewOption,proto3,enum=face.FacePreviewOption" json:"previewOption,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *FaceConfig) Reset()         { *m = FaceConfig{} }
func (m *FaceConfig) String() string { return proto.CompactTextString(m) }
func (*FaceConfig) ProtoMessage()    {}
func (*FaceConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_543a5193e84d47c5, []int{18}
}

func (m *FaceConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FaceConfig.Unmarshal(m, b)
}
func (m *FaceConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FaceConfig.Marshal(b, m, deterministic)
}
func (m *FaceConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FaceConfig.Merge(m, src)
}
func (m *FaceConfig) XXX_Size() int {
	return xxx_messageInfo_FaceConfig.Size(m)
}
func (m *FaceConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_FaceConfig.DiscardUnknown(m)
}

var xxx_messageInfo_FaceConfig proto.InternalMessageInfo

func (m *FaceConfig) GetSecurityLevel() FaceSecurityLevel {
	if m != nil {
		return m.SecurityLevel
	}
	return FaceSecurityLevel_BS2_FACE_SECURITY_NORMAL
}

func (m *FaceConfig) GetLightCondition() FaceLightCondition {
	if m != nil {
		return m.LightCondition
	}
	return FaceLightCondition_BS2_FACE_LIGHT_CONDITION_INDOOR
}

func (m *FaceConfig) GetEnrollThreshold() FaceEnrollThreshold {
	if m != nil {
		return m.EnrollThreshold
	}
	return FaceEnrollThreshold_BS2_FACE_ENROLL_THRESHOLD_0
}

func (m *FaceConfig) GetDetectSensitivity() FaceDetectSensitivity {
	if m != nil {
		return m.DetectSensitivity
	}
	return FaceDetectSensitivity_BS2_FACE_DETECT_SENSITIVITY_OFF
}

func (m *FaceConfig) GetEnrollTimeout() uint32 {
	if m != nil {
		return m.EnrollTimeout
	}
	return 0
}

func (m *FaceConfig) GetLFDLevel() FaceLFDLevel {
	if m != nil {
		return m.LFDLevel
	}
	return FaceLFDLevel_BS2_FACE_LFD_LEVEL_OFF
}

func (m *FaceConfig) GetQuickEnrollment() bool {
	if m != nil {
		return m.QuickEnrollment
	}
	return false
}

func (m *FaceConfig) GetPreviewOption() FacePreviewOption {
	if m != nil {
		return m.PreviewOption
	}
	return FacePreviewOption_BS2_FACE_PREVIEW_NONE
}

type GetConfigRequest struct {
	DeviceID             uint32   `protobuf:"varint,1,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConfigRequest) Reset()         { *m = GetConfigRequest{} }
func (m *GetConfigRequest) String() string { return proto.CompactTextString(m) }
func (*GetConfigRequest) ProtoMessage()    {}
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_543a5193e84d47c5, []int{19}
}

func (m *GetConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigRequest.Unmarshal(m, b)
}
func (m *GetConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigRequest.Marshal(b, m, deterministic)
}
func (m *GetConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigRequest.Merge(m, src)
}
func (m *GetConfigRequest) XXX_Size() int {
	return xxx_messageInfo_GetConfigRequest.Size(m)
}
func (m *GetConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigRequest proto.InternalMessageInfo

func (m *GetConfigRequest) GetDeviceID() uint32 {
	if m != nil {
		return m.DeviceID
	}
	return 0
}

type GetConfigResponse struct {
	Config               *FaceConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetConfigResponse) Reset()         { *m = GetConfigResponse{} }
func (m *GetConfigResponse) String() string { return proto.CompactTextString(m) }
func (*GetConfigResponse) ProtoMessage()    {}
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_543a5193e84d47c5, []int{20}
}

func (m *GetConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigResponse.Unmarshal(m, b)
}
func (m *GetConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigResponse.Marshal(b, m, deterministic)
}
func (m *GetConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigResponse.Merge(m, src)
}
func (m *GetConfigResponse) XXX_Size() int {
	return xxx_messageInfo_GetConfigResponse.Size(m)
}
func (m *GetConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigResponse proto.InternalMessageInfo

func (m *GetConfigResponse) GetConfig() *FaceConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

type SetConfigRequest struct {
	DeviceID             uint32      `protobuf:"varint,1,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	Config               *FaceConfig `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SetConfigRequest) Reset()         { *m = SetConfigRequest{} }
func (m *SetConfigRequest) String() string { return proto.CompactTextString(m) }
func (*SetConfigRequest) ProtoMessage()    {}
func (*SetConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_543a5193e84d47c5, []int{21}
}

func (m *SetConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetConfigRequest.Unmarshal(m, b)
}
func (m *SetConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetConfigRequest.Marshal(b, m, deterministic)
}
func (m *SetConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetConfigRequest.Merge(m, src)
}
func (m *SetConfigRequest) XXX_Size() int {
	return xxx_messageInfo_SetConfigRequest.Size(m)
}
func (m *SetConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetConfigRequest proto.InternalMessageInfo

func (m *SetConfigRequest) GetDeviceID() uint32 {
	if m != nil {
		return m.DeviceID
	}
	return 0
}

func (m *SetConfigRequest) GetConfig() *FaceConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

type SetConfigResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetConfigResponse) Reset()         { *m = SetConfigResponse{} }
func (m *SetConfigResponse) String() string { return proto.CompactTextString(m) }
func (*SetConfigResponse) ProtoMessage()    {}
func (*SetConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_543a5193e84d47c5, []int{22}
}

func (m *SetConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetConfigResponse.Unmarshal(m, b)
}
func (m *SetConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetConfigResponse.Marshal(b, m, deterministic)
}
func (m *SetConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetConfigResponse.Merge(m, src)
}
func (m *SetConfigResponse) XXX_Size() int {
	return xxx_messageInfo_SetConfigResponse.Size(m)
}
func (m *SetConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetConfigResponse proto.InternalMessageInfo

type SetConfigMultiRequest struct {
	DeviceIDs            []uint32    `protobuf:"varint,1,rep,packed,name=deviceIDs,proto3" json:"deviceIDs,omitempty"`
	Config               *FaceConfig `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SetConfigMultiRequest) Reset()         { *m = SetConfigMultiRequest{} }
func (m *SetConfigMultiRequest) String() string { return proto.CompactTextString(m) }
func (*SetConfigMultiRequest) ProtoMessage()    {}
func (*SetConfigMultiRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_543a5193e84d47c5, []int{23}
}

func (m *SetConfigMultiRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetConfigMultiRequest.Unmarshal(m, b)
}
func (m *SetConfigMultiRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetConfigMultiRequest.Marshal(b, m, deterministic)
}
func (m *SetConfigMultiRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetConfigMultiRequest.Merge(m, src)
}
func (m *SetConfigMultiRequest) XXX_Size() int {
	return xxx_messageInfo_SetConfigMultiRequest.Size(m)
}
func (m *SetConfigMultiRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetConfigMultiRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetConfigMultiRequest proto.InternalMessageInfo

func (m *SetConfigMultiRequest) GetDeviceIDs() []uint32 {
	if m != nil {
		return m.DeviceIDs
	}
	return nil
}

func (m *SetConfigMultiRequest) GetConfig() *FaceConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

type SetConfigMultiResponse struct {
	DeviceErrors         []*err.ErrorResponse `protobuf:"bytes,1,rep,name=deviceErrors,proto3" json:"deviceErrors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SetConfigMultiResponse) Reset()         { *m = SetConfigMultiResponse{} }
func (m *SetConfigMultiResponse) String() string { return proto.CompactTextString(m) }
func (*SetConfigMultiResponse) ProtoMessage()    {}
func (*SetConfigMultiResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_543a5193e84d47c5, []int{24}
}

func (m *SetConfigMultiResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetConfigMultiResponse.Unmarshal(m, b)
}
func (m *SetConfigMultiResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetConfigMultiResponse.Marshal(b, m, deterministic)
}
func (m *SetConfigMultiResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetConfigMultiResponse.Merge(m, src)
}
func (m *SetConfigMultiResponse) XXX_Size() int {
	return xxx_messageInfo_SetConfigMultiResponse.Size(m)
}
func (m *SetConfigMultiResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetConfigMultiResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetConfigMultiResponse proto.InternalMessageInfo

func (m *SetConfigMultiResponse) GetDeviceErrors() []*err.ErrorResponse {
	if m != nil {
		return m.DeviceErrors
	}
	return nil
}

func init() {
	proto.RegisterEnum("face.FaceSecurityLevel", FaceSecurityLevel_name, FaceSecurityLevel_value)
	proto.RegisterEnum("face.FaceEnrollThreshold", FaceEnrollThreshold_name, FaceEnrollThreshold_value)
	proto.RegisterEnum("face.FaceLightCondition", FaceLightCondition_name, FaceLightCondition_value)
	proto.RegisterEnum("face.FaceDetectSensitivity", FaceDetectSensitivity_name, FaceDetectSensitivity_value)
	proto.RegisterEnum("face.FaceLFDLevel", FaceLFDLevel_name, FaceLFDLevel_value)
	proto.RegisterEnum("face.FacePreviewOption", FacePreviewOption_name, FacePreviewOption_value)
	proto.RegisterType((*FaceData)(nil), "face.FaceData")
	proto.RegisterType((*ScanRequest)(nil), "face.ScanRequest")
	proto.RegisterType((*ScanResponse)(nil), "face.ScanResponse")
	proto.RegisterType((*AuthGroup)(nil), "face.AuthGroup")
	proto.RegisterType((*GetAuthGroupRequest)(nil), "face.GetAuthGroupRequest")
	proto.RegisterType((*GetAuthGroupResponse)(nil), "face.GetAuthGroupResponse")
	proto.RegisterType((*AddAuthGroupRequest)(nil), "face.AddAuthGroupRequest")
	proto.RegisterType((*AddAuthGroupResponse)(nil), "face.AddAuthGroupResponse")
	proto.RegisterType((*AddAuthGroupMultiRequest)(nil), "face.AddAuthGroupMultiRequest")
	proto.RegisterType((*AddAuthGroupMultiResponse)(nil), "face.AddAuthGroupMultiResponse")
	proto.RegisterType((*DeleteAuthGroupRequest)(nil), "face.DeleteAuthGroupRequest")
	proto.RegisterType((*DeleteAuthGroupResponse)(nil), "face.DeleteAuthGroupResponse")
	proto.RegisterType((*DeleteAuthGroupMultiRequest)(nil), "face.DeleteAuthGroupMultiRequest")
	proto.RegisterType((*DeleteAuthGroupMultiResponse)(nil), "face.DeleteAuthGroupMultiResponse")
	proto.RegisterType((*DeleteAllAuthGroupRequest)(nil), "face.DeleteAllAuthGroupRequest")
	proto.RegisterType((*DeleteAllAuthGroupResponse)(nil), "face.DeleteAllAuthGroupResponse")
	proto.RegisterType((*DeleteAllAuthGroupMultiRequest)(nil), "face.DeleteAllAuthGroupMultiRequest")
	proto.RegisterType((*DeleteAllAuthGroupMultiResponse)(nil), "face.DeleteAllAuthGroupMultiResponse")
	proto.RegisterType((*FaceConfig)(nil), "face.FaceConfig")
	proto.RegisterType((*GetConfigRequest)(nil), "face.GetConfigRequest")
	proto.RegisterType((*GetConfigResponse)(nil), "face.GetConfigResponse")
	proto.RegisterType((*SetConfigRequest)(nil), "face.SetConfigRequest")
	proto.RegisterType((*SetConfigResponse)(nil), "face.SetConfigResponse")
	proto.RegisterType((*SetConfigMultiRequest)(nil), "face.SetConfigMultiRequest")
	proto.RegisterType((*SetConfigMultiResponse)(nil), "face.SetConfigMultiResponse")
}

func init() { proto.RegisterFile("face.proto", fileDescriptor_543a5193e84d47c5) }

var fileDescriptor_543a5193e84d47c5 = []byte{
	// 1296 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x58, 0x6d, 0x6f, 0xda, 0x56,
	0x14, 0x8e, 0x81, 0xa4, 0x70, 0xf2, 0x76, 0x73, 0x93, 0x26, 0xe0, 0xa4, 0x0d, 0x75, 0xdb, 0x0d,
	0x55, 0x1a, 0x59, 0xe9, 0xd6, 0x6e, 0xd3, 0x3a, 0x8d, 0x62, 0x93, 0x58, 0x75, 0x70, 0x74, 0x4d,
	0x92, 0x75, 0xd2, 0x84, 0x28, 0xdc, 0x24, 0x56, 0x01, 0x53, 0xdb, 0x64, 0xeb, 0x1f, 0xd8, 0x87,
	0x7d, 0xdf, 0x5f, 0xd8, 0xdf, 0x99, 0xb4, 0xcf, 0xfd, 0x31, 0x93, 0x5f, 0xf1, 0x1b, 0x4e, 0x50,
	0xbe, 0x99, 0xf3, 0x3c, 0xe7, 0x39, 0x2f, 0xbe, 0x3e, 0xf7, 0x5e, 0x00, 0x2e, 0xba, 0x3d, 0x5a,
	0x1d, 0xeb, 0x9a, 0xa9, 0xe1, 0x9c, 0xf5, 0xcc, 0x16, 0xa8, 0xae, 0x3b, 0x06, 0x6e, 0x0c, 0xf9,
	0x66, 0xb7, 0x47, 0xf9, 0xae, 0xd9, 0xc5, 0x5b, 0xb0, 0xa8, 0x8e, 0xfa, 0xf4, 0x8f, 0x22, 0x53,
	0x66, 0x2a, 0x8b, 0xc4, 0xf9, 0x81, 0x31, 0xe4, 0x2e, 0x06, 0xdd, 0xcb, 0x62, 0xa6, 0xcc, 0x54,
	0x56, 0x89, 0xfd, 0x8c, 0xf7, 0xa0, 0x60, 0xd2, 0xe1, 0x78, 0xd0, 0x35, 0xa9, 0x51, 0xcc, 0x96,
	0xb3, 0x95, 0x15, 0x32, 0x35, 0x58, 0xa8, 0x3a, 0xec, 0x5e, 0xda, 0xa2, 0xc5, 0xc5, 0x32, 0x63,
	0xa1, 0xbe, 0x81, 0x1b, 0xc1, 0xb2, 0xd2, 0xeb, 0x8e, 0x08, 0xfd, 0x38, 0xa1, 0x86, 0x89, 0x59,
	0xc8, 0xf7, 0xe9, 0xb5, 0xda, 0xa3, 0x22, 0x6f, 0xc7, 0x5d, 0x25, 0xfe, 0x6f, 0xdc, 0x80, 0x75,
	0x3a, 0xd2, 0xb5, 0xc1, 0xa0, 0x7d, 0xa5, 0x53, 0xe3, 0x4a, 0x1b, 0xf4, 0xed, 0x2c, 0xd6, 0x6a,
	0xa5, 0xaa, 0x5d, 0x93, 0x95, 0xb9, 0x10, 0x26, 0x90, 0xa8, 0x07, 0xf7, 0x03, 0xac, 0x38, 0xf1,
	0x8c, 0xb1, 0x36, 0x32, 0x28, 0x7e, 0x06, 0xf9, 0x0b, 0xb7, 0x62, 0x5b, 0x6d, 0xb9, 0xb6, 0x36,
	0x55, 0xb3, 0xac, 0xc4, 0xc7, 0xb9, 0x03, 0x28, 0xd4, 0x27, 0xe6, 0xd5, 0xa1, 0xae, 0x4d, 0xc6,
	0x78, 0x0d, 0x32, 0x7e, 0x8e, 0x19, 0x91, 0xb7, 0x1a, 0x33, 0xea, 0x0e, 0xa9, 0x2d, 0x52, 0x20,
	0xf6, 0x33, 0xf7, 0x1c, 0x36, 0x0f, 0xa9, 0xe9, 0xfb, 0xdc, 0xa2, 0x48, 0xee, 0x10, 0xb6, 0xc2,
	0x2e, 0x6e, 0x9e, 0x07, 0x00, 0x5d, 0xcf, 0x68, 0x14, 0x99, 0x72, 0xb6, 0xb2, 0x5c, 0x5b, 0x77,
	0x32, 0x9d, 0x92, 0x03, 0x14, 0xee, 0x3d, 0x6c, 0xd6, 0xfb, 0xfd, 0x79, 0x62, 0x47, 0x62, 0x64,
	0x6e, 0x8e, 0xb1, 0x0d, 0x5b, 0xe1, 0x18, 0x4e, 0xb2, 0x9c, 0x0a, 0xc5, 0xa0, 0xfd, 0x78, 0x32,
	0x30, 0x55, 0x2f, 0x81, 0x3d, 0x28, 0x78, 0x01, 0x9d, 0x3a, 0x56, 0xc9, 0xd4, 0x30, 0x7f, 0x0a,
	0x0a, 0x94, 0x12, 0x42, 0xb9, 0x4d, 0x7b, 0x09, 0x2b, 0x8e, 0xb4, 0xa0, 0xeb, 0x9a, 0xee, 0xb5,
	0x0d, 0x57, 0xad, 0x05, 0x6f, 0x9b, 0x3c, 0x26, 0x09, 0xf1, 0xb8, 0x13, 0xd8, 0xe6, 0xe9, 0x80,
	0x9a, 0x74, 0xae, 0xf6, 0xb1, 0x90, 0xbf, 0xb4, 0xb8, 0x56, 0x61, 0x19, 0xbb, 0x30, 0xff, 0x37,
	0x57, 0x82, 0x9d, 0x98, 0xa2, 0xdb, 0xac, 0x73, 0xd8, 0x8d, 0x40, 0x73, 0xf4, 0x2b, 0x2d, 0xe6,
	0x19, 0xec, 0x25, 0x0b, 0xdf, 0xb1, 0x3b, 0xaf, 0xa0, 0xe4, 0xea, 0x0e, 0x06, 0x73, 0xad, 0xed,
	0x3d, 0x60, 0x93, 0x1c, 0xdd, 0x3e, 0xfc, 0x04, 0x0f, 0xe3, 0xe8, 0xed, 0x5b, 0xc1, 0xbd, 0x83,
	0xfd, 0x99, 0xfe, 0x77, 0xac, 0xf8, 0x73, 0x16, 0xc0, 0x9a, 0x07, 0x0d, 0x6d, 0x74, 0xa1, 0x5e,
	0xe2, 0xd7, 0xb0, 0x6a, 0xd0, 0xde, 0x44, 0x57, 0xcd, 0x4f, 0x12, 0xbd, 0xa6, 0x03, 0xbb, 0xd0,
	0xb5, 0xda, 0xce, 0x74, 0x70, 0x28, 0x41, 0x98, 0x84, 0xd9, 0xf8, 0x67, 0x58, 0x1b, 0xa8, 0x97,
	0x57, 0x66, 0x43, 0x1b, 0xf5, 0x55, 0x53, 0xd5, 0x46, 0xee, 0x18, 0x2b, 0x4e, 0xfd, 0xa5, 0x10,
	0x4e, 0x22, 0xfc, 0xa4, 0x49, 0x98, 0x9d, 0x77, 0x12, 0x62, 0x11, 0x36, 0xfa, 0xd4, 0xa4, 0x3d,
	0x53, 0xa1, 0x23, 0x43, 0x35, 0xd5, 0x6b, 0xd5, 0xfc, 0x54, 0xcc, 0xd9, 0x32, 0xbb, 0x81, 0x11,
	0x18, 0xa5, 0x90, 0xb8, 0x17, 0x7e, 0x02, 0xab, 0xae, 0xba, 0x3a, 0xa4, 0xda, 0xc4, 0xb4, 0xc7,
	0xfc, 0x2a, 0x09, 0x1b, 0x71, 0x15, 0xf2, 0x52, 0x93, 0x77, 0x3a, 0xb6, 0x64, 0xc7, 0xc1, 0x81,
	0x8a, 0x5d, 0x84, 0xf8, 0x1c, 0x5c, 0x81, 0xf5, 0x8f, 0x13, 0xb5, 0xf7, 0xc1, 0xa9, 0x64, 0x48,
	0x47, 0x66, 0xf1, 0x5e, 0x99, 0xa9, 0xe4, 0x49, 0xd4, 0x6c, 0xbd, 0x90, 0xb1, 0x4e, 0xaf, 0x55,
	0xfa, 0xbb, 0x3c, 0xb6, 0x1b, 0x9a, 0x8f, 0xbe, 0x90, 0x93, 0x20, 0x4c, 0xc2, 0x6c, 0xae, 0x0a,
	0xe8, 0x90, 0x9a, 0xce, 0xcb, 0xbd, 0xcd, 0x3a, 0x7e, 0x0d, 0x1b, 0x01, 0xbe, 0xbb, 0xb6, 0x2a,
	0xb0, 0xd4, 0xb3, 0x2d, 0x36, 0x7d, 0xb9, 0x86, 0xa6, 0xc1, 0x5d, 0xa6, 0x8b, 0x73, 0xbf, 0x00,
	0x52, 0xe6, 0x08, 0x17, 0x50, 0xce, 0xdc, 0xa0, 0xbc, 0x09, 0x1b, 0x4a, 0x34, 0x31, 0xae, 0x03,
	0xf7, 0x7d, 0xe3, 0x1c, 0x93, 0xe5, 0xf6, 0x51, 0x4f, 0x60, 0x3b, 0x1a, 0xe0, 0x6e, 0xdf, 0xdb,
	0xb3, 0xbf, 0x19, 0xd8, 0x88, 0x7d, 0x46, 0x78, 0x0f, 0x8a, 0x6f, 0x94, 0x5a, 0xa7, 0x59, 0x6f,
	0x08, 0x1d, 0x45, 0x68, 0x9c, 0x12, 0xb1, 0xfd, 0xae, 0xd3, 0x92, 0xc9, 0x71, 0x5d, 0x42, 0x0b,
	0xc9, 0xa8, 0xfd, 0x20, 0x20, 0x06, 0x3f, 0x82, 0x07, 0x71, 0xf4, 0x58, 0x26, 0x82, 0x47, 0xc9,
	0xe0, 0x07, 0x50, 0x8a, 0x53, 0x78, 0xa1, 0x59, 0x3f, 0x95, 0xda, 0x68, 0x81, 0xcd, 0x20, 0xe6,
	0xd9, 0x5f, 0x59, 0xd8, 0x4c, 0xf8, 0xb6, 0xf0, 0x3e, 0xec, 0xfa, 0xae, 0x42, 0x8b, 0xc8, 0x92,
	0xd4, 0x69, 0x1f, 0x11, 0x41, 0x39, 0x92, 0x25, 0xbe, 0xf3, 0x35, 0x5a, 0x48, 0x27, 0x3c, 0x47,
	0x4c, 0x3a, 0xa1, 0x86, 0x32, 0xe9, 0x84, 0x17, 0x28, 0x9b, 0x4e, 0xf8, 0x06, 0xe5, 0xd2, 0x09,
	0xdf, 0xa2, 0xc5, 0x74, 0xc2, 0x4b, 0xb4, 0x94, 0x4e, 0x78, 0x85, 0xee, 0xa5, 0x13, 0xbe, 0x43,
	0xf9, 0x74, 0xc2, 0xf7, 0xa8, 0x80, 0x9f, 0xc2, 0xa3, 0xd9, 0x04, 0xef, 0x65, 0xe4, 0xec, 0x97,
	0xf1, 0x2f, 0x03, 0x38, 0x3e, 0x2b, 0xf1, 0x63, 0xd8, 0xf7, 0x15, 0x24, 0xf1, 0xf0, 0xa8, 0xdd,
	0x69, 0xc8, 0x2d, 0x5e, 0x6c, 0x8b, 0x72, 0xab, 0x23, 0xb6, 0x78, 0x59, 0x26, 0x68, 0x01, 0x3f,
	0x81, 0xf2, 0x4c, 0x92, 0x7c, 0xda, 0xb6, 0x59, 0xe1, 0x45, 0x13, 0x65, 0xd5, 0x4f, 0xdb, 0x32,
	0xca, 0xa4, 0x52, 0xf8, 0x3a, 0x79, 0x8b, 0xb2, 0xa9, 0xb1, 0xc2, 0xcb, 0xeb, 0x33, 0x03, 0xf7,
	0x13, 0x67, 0x6e, 0xa8, 0x28, 0x5e, 0x68, 0x0b, 0x8d, 0x76, 0x47, 0x11, 0x5a, 0x8a, 0xd8, 0x16,
	0xcf, 0xac, 0x55, 0x2a, 0x37, 0x9b, 0x68, 0xe1, 0x26, 0x92, 0x24, 0x9f, 0x23, 0x06, 0x7f, 0x01,
	0x5c, 0x1a, 0xe9, 0x58, 0xe4, 0x79, 0xc9, 0xfa, 0x1a, 0x82, 0x59, 0x27, 0xf0, 0x8e, 0xc4, 0xc3,
	0x23, 0x94, 0xc5, 0x5f, 0xc2, 0xe3, 0x34, 0x96, 0x57, 0x5e, 0xc6, 0x2e, 0xef, 0x1f, 0x06, 0x56,
	0x82, 0xa3, 0x1e, 0xb3, 0xb0, 0x3d, 0xed, 0x4c, 0x93, 0xef, 0x48, 0xc2, 0x99, 0x20, 0xb9, 0xc5,
	0x24, 0x63, 0x4e, 0x0d, 0xc1, 0x2f, 0x75, 0x8a, 0xf9, 0xa9, 0xef, 0xc2, 0x4e, 0x02, 0xec, 0x66,
	0xfc, 0x10, 0xd8, 0x04, 0x30, 0xfc, 0x1e, 0xfe, 0x74, 0xc7, 0x4f, 0x68, 0xd3, 0xc0, 0x25, 0xb8,
	0xef, 0x7b, 0x9e, 0x10, 0xe1, 0x4c, 0x14, 0xce, 0x3b, 0x2d, 0xb9, 0x25, 0xa0, 0x85, 0x44, 0xe8,
	0xa8, 0x2e, 0x35, 0x11, 0x93, 0x08, 0x35, 0x4f, 0x25, 0x09, 0x65, 0x42, 0x13, 0xcb, 0x83, 0xbc,
	0x44, 0x18, 0x2b, 0x91, 0xda, 0x7f, 0x4b, 0x90, 0xb3, 0x12, 0xc1, 0x5f, 0x41, 0xce, 0xba, 0xb5,
	0xe0, 0x0d, 0x67, 0x08, 0x07, 0x6e, 0x4c, 0x2c, 0x0e, 0x9a, 0xdc, 0xb9, 0xfb, 0x23, 0x14, 0xfc,
	0x0d, 0x0a, 0x6f, 0x3b, 0x84, 0xe8, 0x0e, 0xc7, 0xee, 0xc4, 0xec, 0x53, 0x6f, 0x25, 0xea, 0xad,
	0xcc, 0xf0, 0x8e, 0x6d, 0x37, 0xf8, 0x2d, 0xac, 0x85, 0x77, 0x03, 0xbc, 0x1b, 0xa1, 0x06, 0x37,
	0x21, 0x76, 0x2f, 0x19, 0x74, 0xc5, 0x04, 0x58, 0x09, 0xde, 0x86, 0x70, 0xc9, 0xcf, 0x39, 0x7a,
	0xf0, 0x64, 0xd9, 0x24, 0x68, 0x2a, 0x13, 0xbc, 0x24, 0x78, 0x32, 0x09, 0xf7, 0x23, 0x4f, 0x26,
	0xe9, 0x5a, 0x83, 0xdb, 0xb0, 0x11, 0xbb, 0x6b, 0xe0, 0x87, 0x71, 0x87, 0x50, 0x81, 0xfb, 0x33,
	0x71, 0x57, 0xb5, 0x05, 0xeb, 0x91, 0x63, 0x3a, 0x76, 0x9b, 0x92, 0x7c, 0x07, 0x61, 0x1f, 0xcc,
	0x40, 0x5d, 0xbd, 0xdf, 0x60, 0x2b, 0xe9, 0xd8, 0x8f, 0x1f, 0x25, 0xba, 0x85, 0x72, 0xe5, 0xd2,
	0x28, 0xae, 0xfc, 0x39, 0xe0, 0xf8, 0x31, 0x1b, 0xef, 0x87, 0x3c, 0xe3, 0xf7, 0x02, 0xb6, 0x3c,
	0x9b, 0xe0, 0x0a, 0x5f, 0xf8, 0x57, 0xa4, 0xe8, 0xf9, 0x1d, 0x3f, 0x99, 0xe5, 0x1c, 0xca, 0xfe,
	0xe9, 0x0d, 0x2c, 0x27, 0xce, 0x9b, 0xe7, 0xb0, 0xd3, 0xd3, 0x86, 0x55, 0x63, 0x32, 0xd6, 0xe9,
	0xb0, 0xab, 0x8e, 0x7a, 0x55, 0xa3, 0xff, 0xc1, 0x76, 0x3d, 0x61, 0x7e, 0xdd, 0x7a, 0xaf, 0x6a,
	0x86, 0xd9, 0xd5, 0x0f, 0x0c, 0xaa, 0x5b, 0x07, 0x92, 0x03, 0xcb, 0xfe, 0x7e, 0xc9, 0xfe, 0x77,
	0xe4, 0xc5, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0x1c, 0x1d, 0xe3, 0xd5, 0x3c, 0x11, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FaceClient is the client API for Face service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FaceClient interface {
	Scan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (*ScanResponse, error)
	GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error)
	SetConfig(ctx context.Context, in *SetConfigRequest, opts ...grpc.CallOption) (*SetConfigResponse, error)
	SetConfigMulti(ctx context.Context, in *SetConfigMultiRequest, opts ...grpc.CallOption) (*SetConfigMultiResponse, error)
	GetAuthGroup(ctx context.Context, in *GetAuthGroupRequest, opts ...grpc.CallOption) (*GetAuthGroupResponse, error)
	AddAuthGroup(ctx context.Context, in *AddAuthGroupRequest, opts ...grpc.CallOption) (*AddAuthGroupResponse, error)
	AddAuthGroupMulti(ctx context.Context, in *AddAuthGroupMultiRequest, opts ...grpc.CallOption) (*AddAuthGroupMultiResponse, error)
	DeleteAuthGroup(ctx context.Context, in *DeleteAuthGroupRequest, opts ...grpc.CallOption) (*DeleteAuthGroupResponse, error)
	DeleteAuthGroupMulti(ctx context.Context, in *DeleteAuthGroupMultiRequest, opts ...grpc.CallOption) (*DeleteAuthGroupMultiResponse, error)
	DeleteAllAuthGroup(ctx context.Context, in *DeleteAllAuthGroupRequest, opts ...grpc.CallOption) (*DeleteAllAuthGroupResponse, error)
	DeleteAllAuthGroupMulti(ctx context.Context, in *DeleteAllAuthGroupMultiRequest, opts ...grpc.CallOption) (*DeleteAllAuthGroupMultiResponse, error)
}

type faceClient struct {
	cc *grpc.ClientConn
}

func NewFaceClient(cc *grpc.ClientConn) FaceClient {
	return &faceClient{cc}
}

func (c *faceClient) Scan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (*ScanResponse, error) {
	out := new(ScanResponse)
	err := c.cc.Invoke(ctx, "/face.Face/Scan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *faceClient) GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error) {
	out := new(GetConfigResponse)
	err := c.cc.Invoke(ctx, "/face.Face/GetConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *faceClient) SetConfig(ctx context.Context, in *SetConfigRequest, opts ...grpc.CallOption) (*SetConfigResponse, error) {
	out := new(SetConfigResponse)
	err := c.cc.Invoke(ctx, "/face.Face/SetConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *faceClient) SetConfigMulti(ctx context.Context, in *SetConfigMultiRequest, opts ...grpc.CallOption) (*SetConfigMultiResponse, error) {
	out := new(SetConfigMultiResponse)
	err := c.cc.Invoke(ctx, "/face.Face/SetConfigMulti", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *faceClient) GetAuthGroup(ctx context.Context, in *GetAuthGroupRequest, opts ...grpc.CallOption) (*GetAuthGroupResponse, error) {
	out := new(GetAuthGroupResponse)
	err := c.cc.Invoke(ctx, "/face.Face/GetAuthGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *faceClient) AddAuthGroup(ctx context.Context, in *AddAuthGroupRequest, opts ...grpc.CallOption) (*AddAuthGroupResponse, error) {
	out := new(AddAuthGroupResponse)
	err := c.cc.Invoke(ctx, "/face.Face/AddAuthGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *faceClient) AddAuthGroupMulti(ctx context.Context, in *AddAuthGroupMultiRequest, opts ...grpc.CallOption) (*AddAuthGroupMultiResponse, error) {
	out := new(AddAuthGroupMultiResponse)
	err := c.cc.Invoke(ctx, "/face.Face/AddAuthGroupMulti", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *faceClient) DeleteAuthGroup(ctx context.Context, in *DeleteAuthGroupRequest, opts ...grpc.CallOption) (*DeleteAuthGroupResponse, error) {
	out := new(DeleteAuthGroupResponse)
	err := c.cc.Invoke(ctx, "/face.Face/DeleteAuthGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *faceClient) DeleteAuthGroupMulti(ctx context.Context, in *DeleteAuthGroupMultiRequest, opts ...grpc.CallOption) (*DeleteAuthGroupMultiResponse, error) {
	out := new(DeleteAuthGroupMultiResponse)
	err := c.cc.Invoke(ctx, "/face.Face/DeleteAuthGroupMulti", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *faceClient) DeleteAllAuthGroup(ctx context.Context, in *DeleteAllAuthGroupRequest, opts ...grpc.CallOption) (*DeleteAllAuthGroupResponse, error) {
	out := new(DeleteAllAuthGroupResponse)
	err := c.cc.Invoke(ctx, "/face.Face/DeleteAllAuthGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *faceClient) DeleteAllAuthGroupMulti(ctx context.Context, in *DeleteAllAuthGroupMultiRequest, opts ...grpc.CallOption) (*DeleteAllAuthGroupMultiResponse, error) {
	out := new(DeleteAllAuthGroupMultiResponse)
	err := c.cc.Invoke(ctx, "/face.Face/DeleteAllAuthGroupMulti", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FaceServer is the server API for Face service.
type FaceServer interface {
	Scan(context.Context, *ScanRequest) (*ScanResponse, error)
	GetConfig(context.Context, *GetConfigRequest) (*GetConfigResponse, error)
	SetConfig(context.Context, *SetConfigRequest) (*SetConfigResponse, error)
	SetConfigMulti(context.Context, *SetConfigMultiRequest) (*SetConfigMultiResponse, error)
	GetAuthGroup(context.Context, *GetAuthGroupRequest) (*GetAuthGroupResponse, error)
	AddAuthGroup(context.Context, *AddAuthGroupRequest) (*AddAuthGroupResponse, error)
	AddAuthGroupMulti(context.Context, *AddAuthGroupMultiRequest) (*AddAuthGroupMultiResponse, error)
	DeleteAuthGroup(context.Context, *DeleteAuthGroupRequest) (*DeleteAuthGroupResponse, error)
	DeleteAuthGroupMulti(context.Context, *DeleteAuthGroupMultiRequest) (*DeleteAuthGroupMultiResponse, error)
	DeleteAllAuthGroup(context.Context, *DeleteAllAuthGroupRequest) (*DeleteAllAuthGroupResponse, error)
	DeleteAllAuthGroupMulti(context.Context, *DeleteAllAuthGroupMultiRequest) (*DeleteAllAuthGroupMultiResponse, error)
}

func RegisterFaceServer(s *grpc.Server, srv FaceServer) {
	s.RegisterService(&_Face_serviceDesc, srv)
}

func _Face_Scan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaceServer).Scan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/face.Face/Scan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaceServer).Scan(ctx, req.(*ScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Face_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaceServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/face.Face/GetConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaceServer).GetConfig(ctx, req.(*GetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Face_SetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaceServer).SetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/face.Face/SetConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaceServer).SetConfig(ctx, req.(*SetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Face_SetConfigMulti_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetConfigMultiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaceServer).SetConfigMulti(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/face.Face/SetConfigMulti",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaceServer).SetConfigMulti(ctx, req.(*SetConfigMultiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Face_GetAuthGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAuthGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaceServer).GetAuthGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/face.Face/GetAuthGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaceServer).GetAuthGroup(ctx, req.(*GetAuthGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Face_AddAuthGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddAuthGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaceServer).AddAuthGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/face.Face/AddAuthGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaceServer).AddAuthGroup(ctx, req.(*AddAuthGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Face_AddAuthGroupMulti_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddAuthGroupMultiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaceServer).AddAuthGroupMulti(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/face.Face/AddAuthGroupMulti",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaceServer).AddAuthGroupMulti(ctx, req.(*AddAuthGroupMultiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Face_DeleteAuthGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAuthGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaceServer).DeleteAuthGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/face.Face/DeleteAuthGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaceServer).DeleteAuthGroup(ctx, req.(*DeleteAuthGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Face_DeleteAuthGroupMulti_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAuthGroupMultiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaceServer).DeleteAuthGroupMulti(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/face.Face/DeleteAuthGroupMulti",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaceServer).DeleteAuthGroupMulti(ctx, req.(*DeleteAuthGroupMultiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Face_DeleteAllAuthGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAllAuthGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaceServer).DeleteAllAuthGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/face.Face/DeleteAllAuthGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaceServer).DeleteAllAuthGroup(ctx, req.(*DeleteAllAuthGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Face_DeleteAllAuthGroupMulti_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAllAuthGroupMultiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaceServer).DeleteAllAuthGroupMulti(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/face.Face/DeleteAllAuthGroupMulti",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaceServer).DeleteAllAuthGroupMulti(ctx, req.(*DeleteAllAuthGroupMultiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Face_serviceDesc = grpc.ServiceDesc{
	ServiceName: "face.Face",
	HandlerType: (*FaceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Scan",
			Handler:    _Face_Scan_Handler,
		},
		{
			MethodName: "GetConfig",
			Handler:    _Face_GetConfig_Handler,
		},
		{
			MethodName: "SetConfig",
			Handler:    _Face_SetConfig_Handler,
		},
		{
			MethodName: "SetConfigMulti",
			Handler:    _Face_SetConfigMulti_Handler,
		},
		{
			MethodName: "GetAuthGroup",
			Handler:    _Face_GetAuthGroup_Handler,
		},
		{
			MethodName: "AddAuthGroup",
			Handler:    _Face_AddAuthGroup_Handler,
		},
		{
			MethodName: "AddAuthGroupMulti",
			Handler:    _Face_AddAuthGroupMulti_Handler,
		},
		{
			MethodName: "DeleteAuthGroup",
			Handler:    _Face_DeleteAuthGroup_Handler,
		},
		{
			MethodName: "DeleteAuthGroupMulti",
			Handler:    _Face_DeleteAuthGroupMulti_Handler,
		},
		{
			MethodName: "DeleteAllAuthGroup",
			Handler:    _Face_DeleteAllAuthGroup_Handler,
		},
		{
			MethodName: "DeleteAllAuthGroupMulti",
			Handler:    _Face_DeleteAllAuthGroupMulti_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "face.proto",
}
