// Code generated by protoc-gen-go. DO NOT EDIT.
// source: time.proto

package time

import (
	err "biostar/service/err"
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Month int32

const (
	Month_MONTH_JANUARY   Month = 0
	Month_MONTH_FEBRUARY  Month = 1
	Month_MONTH_MARCH     Month = 2
	Month_MONTH_APRIL     Month = 3
	Month_MONTH_MAY       Month = 4
	Month_MONTH_JUNE      Month = 5
	Month_MONTH_JULY      Month = 6
	Month_MONTH_AUGUST    Month = 7
	Month_MONTH_SEPTEMBER Month = 8
	Month_MONTH_OCTOBER   Month = 9
	Month_MONTH_NOVEMBER  Month = 10
	Month_MONTH_DECEMBER  Month = 11
)

var Month_name = map[int32]string{
	0:  "MONTH_JANUARY",
	1:  "MONTH_FEBRUARY",
	2:  "MONTH_MARCH",
	3:  "MONTH_APRIL",
	4:  "MONTH_MAY",
	5:  "MONTH_JUNE",
	6:  "MONTH_JULY",
	7:  "MONTH_AUGUST",
	8:  "MONTH_SEPTEMBER",
	9:  "MONTH_OCTOBER",
	10: "MONTH_NOVEMBER",
	11: "MONTH_DECEMBER",
}

var Month_value = map[string]int32{
	"MONTH_JANUARY":   0,
	"MONTH_FEBRUARY":  1,
	"MONTH_MARCH":     2,
	"MONTH_APRIL":     3,
	"MONTH_MAY":       4,
	"MONTH_JUNE":      5,
	"MONTH_JULY":      6,
	"MONTH_AUGUST":    7,
	"MONTH_SEPTEMBER": 8,
	"MONTH_OCTOBER":   9,
	"MONTH_NOVEMBER":  10,
	"MONTH_DECEMBER":  11,
}

func (x Month) String() string {
	return proto.EnumName(Month_name, int32(x))
}

func (Month) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_49a92d779a28c7fd, []int{0}
}

type Weekday int32

const (
	Weekday_WEEKDAY_SUNDAY    Weekday = 0
	Weekday_WEEKDAY_MONDAY    Weekday = 1
	Weekday_WEEKDAY_TUESDAY   Weekday = 2
	Weekday_WEEKDAY_WEDNESDAY Weekday = 3
	Weekday_WEEKDAY_THURSDAY  Weekday = 4
	Weekday_WEEKDAY_FRIDAY    Weekday = 5
	Weekday_WEEKDAY_SATURDAY  Weekday = 6
)

var Weekday_name = map[int32]string{
	0: "WEEKDAY_SUNDAY",
	1: "WEEKDAY_MONDAY",
	2: "WEEKDAY_TUESDAY",
	3: "WEEKDAY_WEDNESDAY",
	4: "WEEKDAY_THURSDAY",
	5: "WEEKDAY_FRIDAY",
	6: "WEEKDAY_SATURDAY",
}

var Weekday_value = map[string]int32{
	"WEEKDAY_SUNDAY":    0,
	"WEEKDAY_MONDAY":    1,
	"WEEKDAY_TUESDAY":   2,
	"WEEKDAY_WEDNESDAY": 3,
	"WEEKDAY_THURSDAY":  4,
	"WEEKDAY_FRIDAY":    5,
	"WEEKDAY_SATURDAY":  6,
}

func (x Weekday) String() string {
	return proto.EnumName(Weekday_name, int32(x))
}

func (Weekday) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_49a92d779a28c7fd, []int{1}
}

type Ordinal int32

const (
	Ordinal_ORDINAL_FIRST   Ordinal = 0
	Ordinal_ORDINAL_SECOND  Ordinal = 1
	Ordinal_ORDINAL_THIRD   Ordinal = 2
	Ordinal_ORDINAL_FOURTH  Ordinal = 3
	Ordinal_ORDINAL_FIFTH   Ordinal = 4
	Ordinal_ORDINAL_SIXTH   Ordinal = 5
	Ordinal_ORDINAL_SEVENTH Ordinal = 6
	Ordinal_ORDINAL_EIGHTH  Ordinal = 7
	Ordinal_ORDINAL_NINTH   Ordinal = 8
	Ordinal_ORDINAL_TENTH   Ordinal = 9
	Ordinal_ORDINAL_LAST    Ordinal = -1
)

var Ordinal_name = map[int32]string{
	0:  "ORDINAL_FIRST",
	1:  "ORDINAL_SECOND",
	2:  "ORDINAL_THIRD",
	3:  "ORDINAL_FOURTH",
	4:  "ORDINAL_FIFTH",
	5:  "ORDINAL_SIXTH",
	6:  "ORDINAL_SEVENTH",
	7:  "ORDINAL_EIGHTH",
	8:  "ORDINAL_NINTH",
	9:  "ORDINAL_TENTH",
	-1: "ORDINAL_LAST",
}

var Ordinal_value = map[string]int32{
	"ORDINAL_FIRST":   0,
	"ORDINAL_SECOND":  1,
	"ORDINAL_THIRD":   2,
	"ORDINAL_FOURTH":  3,
	"ORDINAL_FIFTH":   4,
	"ORDINAL_SIXTH":   5,
	"ORDINAL_SEVENTH": 6,
	"ORDINAL_EIGHTH":  7,
	"ORDINAL_NINTH":   8,
	"ORDINAL_TENTH":   9,
	"ORDINAL_LAST":    -1,
}

func (x Ordinal) String() string {
	return proto.EnumName(Ordinal_name, int32(x))
}

func (Ordinal) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_49a92d779a28c7fd, []int{2}
}

type GetRequest struct {
	DeviceID             uint32   `protobuf:"varint,1,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_49a92d779a28c7fd, []int{0}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetDeviceID() uint32 {
	if m != nil {
		return m.DeviceID
	}
	return 0
}

type GetResponse struct {
	GMTTime              uint64   `protobuf:"varint,1,opt,name=GMTTime,proto3" json:"GMTTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_49a92d779a28c7fd, []int{1}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetGMTTime() uint64 {
	if m != nil {
		return m.GMTTime
	}
	return 0
}

type SetRequest struct {
	DeviceID             uint32   `protobuf:"varint,1,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	GMTTime              uint64   `protobuf:"varint,2,opt,name=GMTTime,proto3" json:"GMTTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetRequest) Reset()         { *m = SetRequest{} }
func (m *SetRequest) String() string { return proto.CompactTextString(m) }
func (*SetRequest) ProtoMessage()    {}
func (*SetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_49a92d779a28c7fd, []int{2}
}

func (m *SetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetRequest.Unmarshal(m, b)
}
func (m *SetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetRequest.Marshal(b, m, deterministic)
}
func (m *SetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetRequest.Merge(m, src)
}
func (m *SetRequest) XXX_Size() int {
	return xxx_messageInfo_SetRequest.Size(m)
}
func (m *SetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetRequest proto.InternalMessageInfo

func (m *SetRequest) GetDeviceID() uint32 {
	if m != nil {
		return m.DeviceID
	}
	return 0
}

func (m *SetRequest) GetGMTTime() uint64 {
	if m != nil {
		return m.GMTTime
	}
	return 0
}

type SetResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetResponse) Reset()         { *m = SetResponse{} }
func (m *SetResponse) String() string { return proto.CompactTextString(m) }
func (*SetResponse) ProtoMessage()    {}
func (*SetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_49a92d779a28c7fd, []int{3}
}

func (m *SetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetResponse.Unmarshal(m, b)
}
func (m *SetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetResponse.Marshal(b, m, deterministic)
}
func (m *SetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetResponse.Merge(m, src)
}
func (m *SetResponse) XXX_Size() int {
	return xxx_messageInfo_SetResponse.Size(m)
}
func (m *SetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetResponse proto.InternalMessageInfo

type SetMultiRequest struct {
	DeviceIDs            []uint32 `protobuf:"varint,1,rep,packed,name=deviceIDs,proto3" json:"deviceIDs,omitempty"`
	GMTTime              uint64   `protobuf:"varint,2,opt,name=GMTTime,proto3" json:"GMTTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetMultiRequest) Reset()         { *m = SetMultiRequest{} }
func (m *SetMultiRequest) String() string { return proto.CompactTextString(m) }
func (*SetMultiRequest) ProtoMessage()    {}
func (*SetMultiRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_49a92d779a28c7fd, []int{4}
}

func (m *SetMultiRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetMultiRequest.Unmarshal(m, b)
}
func (m *SetMultiRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetMultiRequest.Marshal(b, m, deterministic)
}
func (m *SetMultiRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetMultiRequest.Merge(m, src)
}
func (m *SetMultiRequest) XXX_Size() int {
	return xxx_messageInfo_SetMultiRequest.Size(m)
}
func (m *SetMultiRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetMultiRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetMultiRequest proto.InternalMessageInfo

func (m *SetMultiRequest) GetDeviceIDs() []uint32 {
	if m != nil {
		return m.DeviceIDs
	}
	return nil
}

func (m *SetMultiRequest) GetGMTTime() uint64 {
	if m != nil {
		return m.GMTTime
	}
	return 0
}

type SetMultiResponse struct {
	DeviceErrors         []*err.ErrorResponse `protobuf:"bytes,1,rep,name=deviceErrors,proto3" json:"deviceErrors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SetMultiResponse) Reset()         { *m = SetMultiResponse{} }
func (m *SetMultiResponse) String() string { return proto.CompactTextString(m) }
func (*SetMultiResponse) ProtoMessage()    {}
func (*SetMultiResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_49a92d779a28c7fd, []int{5}
}

func (m *SetMultiResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetMultiResponse.Unmarshal(m, b)
}
func (m *SetMultiResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetMultiResponse.Marshal(b, m, deterministic)
}
func (m *SetMultiResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetMultiResponse.Merge(m, src)
}
func (m *SetMultiResponse) XXX_Size() int {
	return xxx_messageInfo_SetMultiResponse.Size(m)
}
func (m *SetMultiResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetMultiResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetMultiResponse proto.InternalMessageInfo

func (m *SetMultiResponse) GetDeviceErrors() []*err.ErrorResponse {
	if m != nil {
		return m.DeviceErrors
	}
	return nil
}

type TimeConfig struct {
	TimeZone             int32    `protobuf:"varint,1,opt,name=timeZone,proto3" json:"timeZone,omitempty"`
	SyncWithServer       bool     `protobuf:"varint,2,opt,name=syncWithServer,proto3" json:"syncWithServer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimeConfig) Reset()         { *m = TimeConfig{} }
func (m *TimeConfig) String() string { return proto.CompactTextString(m) }
func (*TimeConfig) ProtoMessage()    {}
func (*TimeConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_49a92d779a28c7fd, []int{6}
}

func (m *TimeConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeConfig.Unmarshal(m, b)
}
func (m *TimeConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeConfig.Marshal(b, m, deterministic)
}
func (m *TimeConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeConfig.Merge(m, src)
}
func (m *TimeConfig) XXX_Size() int {
	return xxx_messageInfo_TimeConfig.Size(m)
}
func (m *TimeConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeConfig.DiscardUnknown(m)
}

var xxx_messageInfo_TimeConfig proto.InternalMessageInfo

func (m *TimeConfig) GetTimeZone() int32 {
	if m != nil {
		return m.TimeZone
	}
	return 0
}

func (m *TimeConfig) GetSyncWithServer() bool {
	if m != nil {
		return m.SyncWithServer
	}
	return false
}

type GetConfigRequest struct {
	DeviceID             uint32   `protobuf:"varint,1,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConfigRequest) Reset()         { *m = GetConfigRequest{} }
func (m *GetConfigRequest) String() string { return proto.CompactTextString(m) }
func (*GetConfigRequest) ProtoMessage()    {}
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_49a92d779a28c7fd, []int{7}
}

func (m *GetConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigRequest.Unmarshal(m, b)
}
func (m *GetConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigRequest.Marshal(b, m, deterministic)
}
func (m *GetConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigRequest.Merge(m, src)
}
func (m *GetConfigRequest) XXX_Size() int {
	return xxx_messageInfo_GetConfigRequest.Size(m)
}
func (m *GetConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigRequest proto.InternalMessageInfo

func (m *GetConfigRequest) GetDeviceID() uint32 {
	if m != nil {
		return m.DeviceID
	}
	return 0
}

type GetConfigResponse struct {
	Config               *TimeConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetConfigResponse) Reset()         { *m = GetConfigResponse{} }
func (m *GetConfigResponse) String() string { return proto.CompactTextString(m) }
func (*GetConfigResponse) ProtoMessage()    {}
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_49a92d779a28c7fd, []int{8}
}

func (m *GetConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigResponse.Unmarshal(m, b)
}
func (m *GetConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigResponse.Marshal(b, m, deterministic)
}
func (m *GetConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigResponse.Merge(m, src)
}
func (m *GetConfigResponse) XXX_Size() int {
	return xxx_messageInfo_GetConfigResponse.Size(m)
}
func (m *GetConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigResponse proto.InternalMessageInfo

func (m *GetConfigResponse) GetConfig() *TimeConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

type SetConfigRequest struct {
	DeviceID             uint32      `protobuf:"varint,1,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	Config               *TimeConfig `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SetConfigRequest) Reset()         { *m = SetConfigRequest{} }
func (m *SetConfigRequest) String() string { return proto.CompactTextString(m) }
func (*SetConfigRequest) ProtoMessage()    {}
func (*SetConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_49a92d779a28c7fd, []int{9}
}

func (m *SetConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetConfigRequest.Unmarshal(m, b)
}
func (m *SetConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetConfigRequest.Marshal(b, m, deterministic)
}
func (m *SetConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetConfigRequest.Merge(m, src)
}
func (m *SetConfigRequest) XXX_Size() int {
	return xxx_messageInfo_SetConfigRequest.Size(m)
}
func (m *SetConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetConfigRequest proto.InternalMessageInfo

func (m *SetConfigRequest) GetDeviceID() uint32 {
	if m != nil {
		return m.DeviceID
	}
	return 0
}

func (m *SetConfigRequest) GetConfig() *TimeConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

type SetConfigResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetConfigResponse) Reset()         { *m = SetConfigResponse{} }
func (m *SetConfigResponse) String() string { return proto.CompactTextString(m) }
func (*SetConfigResponse) ProtoMessage()    {}
func (*SetConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_49a92d779a28c7fd, []int{10}
}

func (m *SetConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetConfigResponse.Unmarshal(m, b)
}
func (m *SetConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetConfigResponse.Marshal(b, m, deterministic)
}
func (m *SetConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetConfigResponse.Merge(m, src)
}
func (m *SetConfigResponse) XXX_Size() int {
	return xxx_messageInfo_SetConfigResponse.Size(m)
}
func (m *SetConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetConfigResponse proto.InternalMessageInfo

type SetConfigMultiRequest struct {
	DeviceIDs            []uint32    `protobuf:"varint,1,rep,packed,name=deviceIDs,proto3" json:"deviceIDs,omitempty"`
	Config               *TimeConfig `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SetConfigMultiRequest) Reset()         { *m = SetConfigMultiRequest{} }
func (m *SetConfigMultiRequest) String() string { return proto.CompactTextString(m) }
func (*SetConfigMultiRequest) ProtoMessage()    {}
func (*SetConfigMultiRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_49a92d779a28c7fd, []int{11}
}

func (m *SetConfigMultiRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetConfigMultiRequest.Unmarshal(m, b)
}
func (m *SetConfigMultiRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetConfigMultiRequest.Marshal(b, m, deterministic)
}
func (m *SetConfigMultiRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetConfigMultiRequest.Merge(m, src)
}
func (m *SetConfigMultiRequest) XXX_Size() int {
	return xxx_messageInfo_SetConfigMultiRequest.Size(m)
}
func (m *SetConfigMultiRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetConfigMultiRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetConfigMultiRequest proto.InternalMessageInfo

func (m *SetConfigMultiRequest) GetDeviceIDs() []uint32 {
	if m != nil {
		return m.DeviceIDs
	}
	return nil
}

func (m *SetConfigMultiRequest) GetConfig() *TimeConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

type SetConfigMultiResponse struct {
	DeviceErrors         []*err.ErrorResponse `protobuf:"bytes,1,rep,name=deviceErrors,proto3" json:"deviceErrors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SetConfigMultiResponse) Reset()         { *m = SetConfigMultiResponse{} }
func (m *SetConfigMultiResponse) String() string { return proto.CompactTextString(m) }
func (*SetConfigMultiResponse) ProtoMessage()    {}
func (*SetConfigMultiResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_49a92d779a28c7fd, []int{12}
}

func (m *SetConfigMultiResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetConfigMultiResponse.Unmarshal(m, b)
}
func (m *SetConfigMultiResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetConfigMultiResponse.Marshal(b, m, deterministic)
}
func (m *SetConfigMultiResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetConfigMultiResponse.Merge(m, src)
}
func (m *SetConfigMultiResponse) XXX_Size() int {
	return xxx_messageInfo_SetConfigMultiResponse.Size(m)
}
func (m *SetConfigMultiResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetConfigMultiResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetConfigMultiResponse proto.InternalMessageInfo

func (m *SetConfigMultiResponse) GetDeviceErrors() []*err.ErrorResponse {
	if m != nil {
		return m.DeviceErrors
	}
	return nil
}

type WeekTime struct {
	Year                 uint32   `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Month                Month    `protobuf:"varint,2,opt,name=month,proto3,enum=time.Month" json:"month,omitempty"`
	Ordinal              Ordinal  `protobuf:"varint,3,opt,name=ordinal,proto3,enum=time.Ordinal" json:"ordinal,omitempty"`
	Weekday              Weekday  `protobuf:"varint,4,opt,name=weekday,proto3,enum=time.Weekday" json:"weekday,omitempty"`
	Hour                 uint32   `protobuf:"varint,5,opt,name=hour,proto3" json:"hour,omitempty"`
	Minute               uint32   `protobuf:"varint,6,opt,name=minute,proto3" json:"minute,omitempty"`
	Second               uint32   `protobuf:"varint,7,opt,name=second,proto3" json:"second,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WeekTime) Reset()         { *m = WeekTime{} }
func (m *WeekTime) String() string { return proto.CompactTextString(m) }
func (*WeekTime) ProtoMessage()    {}
func (*WeekTime) Descriptor() ([]byte, []int) {
	return fileDescriptor_49a92d779a28c7fd, []int{13}
}

func (m *WeekTime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WeekTime.Unmarshal(m, b)
}
func (m *WeekTime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WeekTime.Marshal(b, m, deterministic)
}
func (m *WeekTime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WeekTime.Merge(m, src)
}
func (m *WeekTime) XXX_Size() int {
	return xxx_messageInfo_WeekTime.Size(m)
}
func (m *WeekTime) XXX_DiscardUnknown() {
	xxx_messageInfo_WeekTime.DiscardUnknown(m)
}

var xxx_messageInfo_WeekTime proto.InternalMessageInfo

func (m *WeekTime) GetYear() uint32 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *WeekTime) GetMonth() Month {
	if m != nil {
		return m.Month
	}
	return Month_MONTH_JANUARY
}

func (m *WeekTime) GetOrdinal() Ordinal {
	if m != nil {
		return m.Ordinal
	}
	return Ordinal_ORDINAL_FIRST
}

func (m *WeekTime) GetWeekday() Weekday {
	if m != nil {
		return m.Weekday
	}
	return Weekday_WEEKDAY_SUNDAY
}

func (m *WeekTime) GetHour() uint32 {
	if m != nil {
		return m.Hour
	}
	return 0
}

func (m *WeekTime) GetMinute() uint32 {
	if m != nil {
		return m.Minute
	}
	return 0
}

func (m *WeekTime) GetSecond() uint32 {
	if m != nil {
		return m.Second
	}
	return 0
}

type DSTSchedule struct {
	StartTime            *WeekTime `protobuf:"bytes,1,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime              *WeekTime `protobuf:"bytes,2,opt,name=endTime,proto3" json:"endTime,omitempty"`
	TimeOffset           int32     `protobuf:"varint,3,opt,name=timeOffset,proto3" json:"timeOffset,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DSTSchedule) Reset()         { *m = DSTSchedule{} }
func (m *DSTSchedule) String() string { return proto.CompactTextString(m) }
func (*DSTSchedule) ProtoMessage()    {}
func (*DSTSchedule) Descriptor() ([]byte, []int) {
	return fileDescriptor_49a92d779a28c7fd, []int{14}
}

func (m *DSTSchedule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DSTSchedule.Unmarshal(m, b)
}
func (m *DSTSchedule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DSTSchedule.Marshal(b, m, deterministic)
}
func (m *DSTSchedule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DSTSchedule.Merge(m, src)
}
func (m *DSTSchedule) XXX_Size() int {
	return xxx_messageInfo_DSTSchedule.Size(m)
}
func (m *DSTSchedule) XXX_DiscardUnknown() {
	xxx_messageInfo_DSTSchedule.DiscardUnknown(m)
}

var xxx_messageInfo_DSTSchedule proto.InternalMessageInfo

func (m *DSTSchedule) GetStartTime() *WeekTime {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *DSTSchedule) GetEndTime() *WeekTime {
	if m != nil {
		return m.EndTime
	}
	return nil
}

func (m *DSTSchedule) GetTimeOffset() int32 {
	if m != nil {
		return m.TimeOffset
	}
	return 0
}

type DSTConfig struct {
	Schedules            []*DSTSchedule `protobuf:"bytes,1,rep,name=schedules,proto3" json:"schedules,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *DSTConfig) Reset()         { *m = DSTConfig{} }
func (m *DSTConfig) String() string { return proto.CompactTextString(m) }
func (*DSTConfig) ProtoMessage()    {}
func (*DSTConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_49a92d779a28c7fd, []int{15}
}

func (m *DSTConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DSTConfig.Unmarshal(m, b)
}
func (m *DSTConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DSTConfig.Marshal(b, m, deterministic)
}
func (m *DSTConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DSTConfig.Merge(m, src)
}
func (m *DSTConfig) XXX_Size() int {
	return xxx_messageInfo_DSTConfig.Size(m)
}
func (m *DSTConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_DSTConfig.DiscardUnknown(m)
}

var xxx_messageInfo_DSTConfig proto.InternalMessageInfo

func (m *DSTConfig) GetSchedules() []*DSTSchedule {
	if m != nil {
		return m.Schedules
	}
	return nil
}

type GetDSTConfigRequest struct {
	DeviceID             uint32   `protobuf:"varint,1,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDSTConfigRequest) Reset()         { *m = GetDSTConfigRequest{} }
func (m *GetDSTConfigRequest) String() string { return proto.CompactTextString(m) }
func (*GetDSTConfigRequest) ProtoMessage()    {}
func (*GetDSTConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_49a92d779a28c7fd, []int{16}
}

func (m *GetDSTConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDSTConfigRequest.Unmarshal(m, b)
}
func (m *GetDSTConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDSTConfigRequest.Marshal(b, m, deterministic)
}
func (m *GetDSTConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDSTConfigRequest.Merge(m, src)
}
func (m *GetDSTConfigRequest) XXX_Size() int {
	return xxx_messageInfo_GetDSTConfigRequest.Size(m)
}
func (m *GetDSTConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDSTConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDSTConfigRequest proto.InternalMessageInfo

func (m *GetDSTConfigRequest) GetDeviceID() uint32 {
	if m != nil {
		return m.DeviceID
	}
	return 0
}

type GetDSTConfigResponse struct {
	Config               *DSTConfig `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetDSTConfigResponse) Reset()         { *m = GetDSTConfigResponse{} }
func (m *GetDSTConfigResponse) String() string { return proto.CompactTextString(m) }
func (*GetDSTConfigResponse) ProtoMessage()    {}
func (*GetDSTConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_49a92d779a28c7fd, []int{17}
}

func (m *GetDSTConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDSTConfigResponse.Unmarshal(m, b)
}
func (m *GetDSTConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDSTConfigResponse.Marshal(b, m, deterministic)
}
func (m *GetDSTConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDSTConfigResponse.Merge(m, src)
}
func (m *GetDSTConfigResponse) XXX_Size() int {
	return xxx_messageInfo_GetDSTConfigResponse.Size(m)
}
func (m *GetDSTConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDSTConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDSTConfigResponse proto.InternalMessageInfo

func (m *GetDSTConfigResponse) GetConfig() *DSTConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

type SetDSTConfigRequest struct {
	DeviceID             uint32     `protobuf:"varint,1,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	Config               *DSTConfig `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SetDSTConfigRequest) Reset()         { *m = SetDSTConfigRequest{} }
func (m *SetDSTConfigRequest) String() string { return proto.CompactTextString(m) }
func (*SetDSTConfigRequest) ProtoMessage()    {}
func (*SetDSTConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_49a92d779a28c7fd, []int{18}
}

func (m *SetDSTConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetDSTConfigRequest.Unmarshal(m, b)
}
func (m *SetDSTConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetDSTConfigRequest.Marshal(b, m, deterministic)
}
func (m *SetDSTConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetDSTConfigRequest.Merge(m, src)
}
func (m *SetDSTConfigRequest) XXX_Size() int {
	return xxx_messageInfo_SetDSTConfigRequest.Size(m)
}
func (m *SetDSTConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetDSTConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetDSTConfigRequest proto.InternalMessageInfo

func (m *SetDSTConfigRequest) GetDeviceID() uint32 {
	if m != nil {
		return m.DeviceID
	}
	return 0
}

func (m *SetDSTConfigRequest) GetConfig() *DSTConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

type SetDSTConfigResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetDSTConfigResponse) Reset()         { *m = SetDSTConfigResponse{} }
func (m *SetDSTConfigResponse) String() string { return proto.CompactTextString(m) }
func (*SetDSTConfigResponse) ProtoMessage()    {}
func (*SetDSTConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_49a92d779a28c7fd, []int{19}
}

func (m *SetDSTConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetDSTConfigResponse.Unmarshal(m, b)
}
func (m *SetDSTConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetDSTConfigResponse.Marshal(b, m, deterministic)
}
func (m *SetDSTConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetDSTConfigResponse.Merge(m, src)
}
func (m *SetDSTConfigResponse) XXX_Size() int {
	return xxx_messageInfo_SetDSTConfigResponse.Size(m)
}
func (m *SetDSTConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetDSTConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetDSTConfigResponse proto.InternalMessageInfo

type SetDSTConfigMultiRequest struct {
	DeviceIDs            []uint32   `protobuf:"varint,1,rep,packed,name=deviceIDs,proto3" json:"deviceIDs,omitempty"`
	Config               *DSTConfig `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SetDSTConfigMultiRequest) Reset()         { *m = SetDSTConfigMultiRequest{} }
func (m *SetDSTConfigMultiRequest) String() string { return proto.CompactTextString(m) }
func (*SetDSTConfigMultiRequest) ProtoMessage()    {}
func (*SetDSTConfigMultiRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_49a92d779a28c7fd, []int{20}
}

func (m *SetDSTConfigMultiRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetDSTConfigMultiRequest.Unmarshal(m, b)
}
func (m *SetDSTConfigMultiRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetDSTConfigMultiRequest.Marshal(b, m, deterministic)
}
func (m *SetDSTConfigMultiRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetDSTConfigMultiRequest.Merge(m, src)
}
func (m *SetDSTConfigMultiRequest) XXX_Size() int {
	return xxx_messageInfo_SetDSTConfigMultiRequest.Size(m)
}
func (m *SetDSTConfigMultiRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetDSTConfigMultiRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetDSTConfigMultiRequest proto.InternalMessageInfo

func (m *SetDSTConfigMultiRequest) GetDeviceIDs() []uint32 {
	if m != nil {
		return m.DeviceIDs
	}
	return nil
}

func (m *SetDSTConfigMultiRequest) GetConfig() *DSTConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

type SetDSTConfigMultiResponse struct {
	DeviceErrors         []*err.ErrorResponse `protobuf:"bytes,1,rep,name=deviceErrors,proto3" json:"deviceErrors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SetDSTConfigMultiResponse) Reset()         { *m = SetDSTConfigMultiResponse{} }
func (m *SetDSTConfigMultiResponse) String() string { return proto.CompactTextString(m) }
func (*SetDSTConfigMultiResponse) ProtoMessage()    {}
func (*SetDSTConfigMultiResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_49a92d779a28c7fd, []int{21}
}

func (m *SetDSTConfigMultiResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetDSTConfigMultiResponse.Unmarshal(m, b)
}
func (m *SetDSTConfigMultiResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetDSTConfigMultiResponse.Marshal(b, m, deterministic)
}
func (m *SetDSTConfigMultiResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetDSTConfigMultiResponse.Merge(m, src)
}
func (m *SetDSTConfigMultiResponse) XXX_Size() int {
	return xxx_messageInfo_SetDSTConfigMultiResponse.Size(m)
}
func (m *SetDSTConfigMultiResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetDSTConfigMultiResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetDSTConfigMultiResponse proto.InternalMessageInfo

func (m *SetDSTConfigMultiResponse) GetDeviceErrors() []*err.ErrorResponse {
	if m != nil {
		return m.DeviceErrors
	}
	return nil
}

func init() {
	proto.RegisterEnum("time.Month", Month_name, Month_value)
	proto.RegisterEnum("time.Weekday", Weekday_name, Weekday_value)
	proto.RegisterEnum("time.Ordinal", Ordinal_name, Ordinal_value)
	proto.RegisterType((*GetRequest)(nil), "time.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "time.GetResponse")
	proto.RegisterType((*SetRequest)(nil), "time.SetRequest")
	proto.RegisterType((*SetResponse)(nil), "time.SetResponse")
	proto.RegisterType((*SetMultiRequest)(nil), "time.SetMultiRequest")
	proto.RegisterType((*SetMultiResponse)(nil), "time.SetMultiResponse")
	proto.RegisterType((*TimeConfig)(nil), "time.TimeConfig")
	proto.RegisterType((*GetConfigRequest)(nil), "time.GetConfigRequest")
	proto.RegisterType((*GetConfigResponse)(nil), "time.GetConfigResponse")
	proto.RegisterType((*SetConfigRequest)(nil), "time.SetConfigRequest")
	proto.RegisterType((*SetConfigResponse)(nil), "time.SetConfigResponse")
	proto.RegisterType((*SetConfigMultiRequest)(nil), "time.SetConfigMultiRequest")
	proto.RegisterType((*SetConfigMultiResponse)(nil), "time.SetConfigMultiResponse")
	proto.RegisterType((*WeekTime)(nil), "time.WeekTime")
	proto.RegisterType((*DSTSchedule)(nil), "time.DSTSchedule")
	proto.RegisterType((*DSTConfig)(nil), "time.DSTConfig")
	proto.RegisterType((*GetDSTConfigRequest)(nil), "time.GetDSTConfigRequest")
	proto.RegisterType((*GetDSTConfigResponse)(nil), "time.GetDSTConfigResponse")
	proto.RegisterType((*SetDSTConfigRequest)(nil), "time.SetDSTConfigRequest")
	proto.RegisterType((*SetDSTConfigResponse)(nil), "time.SetDSTConfigResponse")
	proto.RegisterType((*SetDSTConfigMultiRequest)(nil), "time.SetDSTConfigMultiRequest")
	proto.RegisterType((*SetDSTConfigMultiResponse)(nil), "time.SetDSTConfigMultiResponse")
}

func init() { proto.RegisterFile("time.proto", fileDescriptor_49a92d779a28c7fd) }

var fileDescriptor_49a92d779a28c7fd = []byte{
	// 1047 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x96, 0xdd, 0x6e, 0xdb, 0x36,
	0x14, 0xc7, 0x27, 0x7f, 0xfb, 0x38, 0x76, 0x68, 0xe6, 0xa3, 0x8e, 0x57, 0x74, 0x9d, 0x2e, 0x96,
	0x20, 0x18, 0x1c, 0x34, 0x03, 0x06, 0x0c, 0xe8, 0x30, 0x38, 0xb1, 0x62, 0xbb, 0x8d, 0xed, 0x80,
	0x94, 0xeb, 0x26, 0x37, 0x81, 0x6b, 0x33, 0x8b, 0x90, 0x58, 0xca, 0x24, 0xb9, 0x43, 0x1e, 0x60,
	0x8f, 0xb1, 0xd7, 0xd9, 0x2b, 0xec, 0x7a, 0x57, 0x7b, 0x8c, 0x0d, 0x24, 0xf5, 0x41, 0x39, 0x4e,
	0xeb, 0xa0, 0xbe, 0x32, 0x7f, 0xfc, 0x9f, 0xff, 0x39, 0xa4, 0x74, 0x28, 0x02, 0xf8, 0xd6, 0x8c,
	0x35, 0xee, 0x5c, 0xc7, 0x77, 0x70, 0x86, 0xff, 0xaf, 0x17, 0x99, 0xeb, 0x4a, 0xa0, 0xef, 0x01,
	0xb4, 0x99, 0x4f, 0xd8, 0x6f, 0x73, 0xe6, 0xf9, 0xb8, 0x0e, 0x85, 0x29, 0xfb, 0x68, 0x4d, 0x58,
	0xb7, 0x55, 0xd3, 0x5e, 0x6a, 0x7b, 0x65, 0x12, 0x8d, 0xf5, 0x5d, 0x28, 0x09, 0xa5, 0x77, 0xe7,
	0xd8, 0x1e, 0xc3, 0x35, 0xc8, 0xb7, 0x7b, 0xa6, 0x69, 0xcd, 0x98, 0x50, 0x66, 0x48, 0x38, 0xd4,
	0x8f, 0x00, 0xe8, 0x4a, 0x96, 0xaa, 0x47, 0x2a, 0xe9, 0x51, 0x86, 0x12, 0x8d, 0x93, 0xe9, 0x5d,
	0x58, 0xa7, 0xcc, 0xef, 0xcd, 0x6f, 0x7d, 0x2b, 0xf4, 0x7d, 0x0e, 0xc5, 0xd0, 0xc7, 0xab, 0x69,
	0x2f, 0xd3, 0x7b, 0x65, 0x12, 0x83, 0x4f, 0x38, 0xbf, 0x01, 0x14, 0x5b, 0x05, 0x6b, 0xf9, 0x11,
	0xd6, 0x64, 0xa8, 0xe1, 0xba, 0x8e, 0x2b, 0xed, 0x4a, 0x87, 0xb8, 0xc1, 0xb7, 0x49, 0xa0, 0x50,
	0x49, 0x12, 0x3a, 0xfd, 0x0c, 0x80, 0x7b, 0x1e, 0x3b, 0xf6, 0x95, 0xf5, 0x2b, 0x5f, 0x29, 0xdf,
	0xdd, 0x0b, 0xc7, 0x96, 0x5b, 0x92, 0x25, 0xd1, 0x18, 0x7f, 0x07, 0x15, 0xef, 0xde, 0x9e, 0x8c,
	0x2c, 0xff, 0x9a, 0x32, 0xf7, 0x23, 0x73, 0x45, 0x59, 0x05, 0xb2, 0x40, 0xf5, 0x06, 0xa0, 0x36,
	0xf3, 0xa5, 0xe1, 0x2a, 0x0f, 0xe5, 0x67, 0xa8, 0x2a, 0xfa, 0x60, 0x39, 0x7b, 0x90, 0x9b, 0x08,
	0x22, 0xe4, 0xa5, 0x43, 0xd4, 0x10, 0x6f, 0x40, 0x5c, 0x2a, 0x09, 0xe6, 0xf5, 0xf7, 0x62, 0x33,
	0x56, 0x4e, 0xa7, 0x38, 0xa7, 0x3e, 0xe3, 0xbc, 0x01, 0x55, 0xba, 0x58, 0x98, 0x7e, 0x09, 0x5b,
	0x11, 0x7c, 0xc2, 0xc3, 0x5c, 0x3d, 0xeb, 0x19, 0x6c, 0x2f, 0x26, 0xf8, 0xc2, 0x47, 0xfc, 0xb7,
	0x06, 0x85, 0x11, 0x63, 0x37, 0x3c, 0x19, 0xc6, 0x90, 0xb9, 0x67, 0x63, 0x37, 0xd8, 0x16, 0xf1,
	0x1f, 0x7f, 0x0b, 0xd9, 0x99, 0x63, 0xfb, 0xd7, 0xa2, 0xb6, 0xca, 0x61, 0x49, 0xd6, 0xd6, 0xe3,
	0x88, 0xc8, 0x19, 0xbc, 0x0b, 0x79, 0xc7, 0x9d, 0x5a, 0xf6, 0xf8, 0xb6, 0x96, 0x16, 0xa2, 0xb2,
	0x14, 0x0d, 0x24, 0x24, 0xe1, 0x2c, 0x17, 0xfe, 0xce, 0xd8, 0xcd, 0x74, 0x7c, 0x5f, 0xcb, 0xa8,
	0xc2, 0x91, 0x84, 0x24, 0x9c, 0xe5, 0x85, 0x5c, 0x3b, 0x73, 0xb7, 0x96, 0x95, 0x85, 0xf0, 0xff,
	0x78, 0x1b, 0x72, 0x33, 0xcb, 0x9e, 0xfb, 0xac, 0x96, 0x13, 0x34, 0x18, 0x71, 0xee, 0xb1, 0x89,
	0x63, 0x4f, 0x6b, 0x79, 0xc9, 0xe5, 0x48, 0xff, 0x43, 0x83, 0x52, 0x8b, 0x9a, 0x74, 0x72, 0xcd,
	0xa6, 0xf3, 0x5b, 0x86, 0xbf, 0x87, 0xa2, 0xe7, 0x8f, 0x5d, 0x3f, 0x6a, 0xe9, 0xd2, 0x61, 0x25,
	0x4e, 0xcf, 0x29, 0x89, 0x05, 0x78, 0x0f, 0xf2, 0xcc, 0x9e, 0x46, 0x0d, 0xf6, 0x50, 0x1b, 0x4e,
	0xe3, 0x17, 0xf2, 0x00, 0x1a, 0x5c, 0x5d, 0x79, 0xcc, 0x17, 0x1b, 0x90, 0x25, 0x0a, 0xd1, 0x5f,
	0x43, 0xb1, 0x45, 0xcd, 0xa0, 0x87, 0x0e, 0xa0, 0xe8, 0x05, 0x05, 0x85, 0xcf, 0xa8, 0x2a, 0x8d,
	0x95, 0x52, 0x49, 0xac, 0xd1, 0x5f, 0xc1, 0x46, 0x9b, 0xf9, 0x91, 0xc1, 0x2a, 0x3d, 0xf3, 0x0b,
	0x6c, 0x26, 0x43, 0x82, 0x57, 0x64, 0x77, 0xa1, 0x6d, 0xd6, 0xa3, 0xc4, 0x0b, 0x6f, 0xd9, 0x05,
	0x6c, 0xd0, 0xa7, 0xe5, 0x54, 0xbc, 0x53, 0x9f, 0xf6, 0xde, 0x86, 0x4d, 0xba, 0xa4, 0x38, 0x7d,
	0x0c, 0x35, 0x95, 0x3f, 0xa1, 0x7b, 0x56, 0x4e, 0x4d, 0x61, 0x67, 0x49, 0x8a, 0x2f, 0xeb, 0x9f,
	0xfd, 0x7f, 0x34, 0xc8, 0x8a, 0x66, 0xc0, 0x55, 0x28, 0xf7, 0x06, 0x7d, 0xb3, 0x73, 0xf9, 0xa6,
	0xd9, 0x1f, 0x36, 0xc9, 0x39, 0xfa, 0x0a, 0x63, 0xa8, 0x48, 0x74, 0x62, 0x1c, 0x11, 0xc1, 0x34,
	0xbc, 0x0e, 0x25, 0xc9, 0x7a, 0x4d, 0x72, 0xdc, 0x41, 0xa9, 0x18, 0x34, 0xcf, 0x48, 0xf7, 0x14,
	0xa5, 0x71, 0x19, 0x8a, 0xa1, 0xe2, 0x1c, 0x65, 0x70, 0x05, 0x20, 0xf0, 0x1d, 0xf6, 0x0d, 0x94,
	0x55, 0xc7, 0xa7, 0xe7, 0x28, 0x87, 0x11, 0xac, 0x05, 0xf1, 0xc3, 0xf6, 0x90, 0x9a, 0x28, 0x8f,
	0x37, 0x60, 0x5d, 0x12, 0x6a, 0x9c, 0x99, 0x46, 0xef, 0xc8, 0x20, 0xa8, 0x10, 0x97, 0x37, 0x38,
	0x36, 0x07, 0x1c, 0x15, 0xe3, 0xf2, 0xfa, 0x83, 0x77, 0x52, 0x06, 0x31, 0x6b, 0x19, 0xc7, 0x92,
	0x95, 0xf6, 0xff, 0xd4, 0x20, 0x3f, 0x8a, 0x3a, 0xb3, 0x32, 0x32, 0x8c, 0xb7, 0xad, 0xe6, 0xf9,
	0x25, 0x1d, 0xf6, 0x5b, 0xcd, 0x60, 0x99, 0x21, 0xeb, 0x0d, 0x04, 0xd3, 0x78, 0x0d, 0x21, 0x33,
	0x87, 0x06, 0xe5, 0x30, 0x85, 0xb7, 0xa0, 0x1a, 0xc2, 0x91, 0xd1, 0xea, 0x4b, 0x9c, 0xc6, 0x9b,
	0x80, 0x22, 0x6d, 0x67, 0x48, 0x04, 0xcd, 0xa8, 0xae, 0x27, 0xa4, 0xcb, 0x59, 0x56, 0x55, 0xd2,
	0xa6, 0x39, 0x24, 0x9c, 0xe6, 0xf6, 0xff, 0xd5, 0x20, 0x1f, 0x9c, 0x35, 0x7c, 0x99, 0x03, 0xd2,
	0xea, 0xf6, 0x9b, 0xa7, 0x97, 0x27, 0x5d, 0x42, 0x4d, 0x59, 0x5e, 0x88, 0xa8, 0x71, 0x3c, 0xe8,
	0xb7, 0x90, 0xa6, 0xca, 0xcc, 0x4e, 0x97, 0xb4, 0x50, 0x4a, 0x95, 0x9d, 0x0c, 0x86, 0xc4, 0xec,
	0xa0, 0x74, 0xd2, 0xed, 0xc4, 0xec, 0xa0, 0x8c, 0x8a, 0x68, 0xf7, 0xbd, 0xd9, 0x41, 0x59, 0xbe,
	0xd6, 0x38, 0xc1, 0x3b, 0xa3, 0x6f, 0x76, 0x50, 0x4e, 0xb5, 0x33, 0xba, 0xed, 0x8e, 0xd9, 0x41,
	0x79, 0x35, 0xb6, 0xdf, 0xe5, 0xb2, 0x42, 0xa2, 0x10, 0x11, 0x59, 0xc4, 0x3b, 0xb0, 0x16, 0xa2,
	0xd3, 0x26, 0x35, 0xd1, 0x7f, 0xe1, 0x4f, 0x3b, 0xfc, 0x2b, 0x03, 0x19, 0x71, 0xe8, 0xec, 0x43,
	0xba, 0xcd, 0x7c, 0x1c, 0x7c, 0x29, 0xe2, 0x1b, 0x4e, 0xbd, 0xaa, 0x90, 0xe0, 0xd5, 0xde, 0x87,
	0x34, 0x8d, 0xb5, 0xf4, 0x81, 0x56, 0xb9, 0x88, 0xe0, 0x9f, 0xa0, 0x10, 0xde, 0x1e, 0xf0, 0x56,
	0x34, 0xad, 0x76, 0x63, 0x7d, 0x7b, 0x11, 0x07, 0xa1, 0xaf, 0xa1, 0x18, 0x7d, 0xaa, 0xf1, 0x76,
	0x54, 0x46, 0xe2, 0x0c, 0xa9, 0x3f, 0x7b, 0xc0, 0xe3, 0x68, 0xba, 0x18, 0x4d, 0x1f, 0x89, 0x7e,
	0xf0, 0xe1, 0xc5, 0x6f, 0xa1, 0x92, 0xfc, 0x2e, 0xe2, 0xaf, 0x17, 0xa4, 0x89, 0x25, 0x3c, 0x5f,
	0x3e, 0x19, 0x98, 0x19, 0xb0, 0xa6, 0x9e, 0x9f, 0x78, 0x27, 0xaa, 0x79, 0xf1, 0x48, 0xac, 0xd7,
	0x97, 0x4d, 0xc5, 0x36, 0x74, 0x89, 0x0d, 0x7d, 0xdc, 0x66, 0xd9, 0xc1, 0x88, 0x4d, 0x71, 0xd1,
	0x48, 0x9e, 0x5a, 0xf8, 0xc5, 0xc3, 0x80, 0xc4, 0x02, 0xbf, 0x79, 0x74, 0x5e, 0xba, 0x1e, 0xbd,
	0x82, 0x67, 0x13, 0x67, 0xd6, 0xf0, 0xe6, 0x77, 0x2e, 0x9b, 0x8d, 0x2d, 0x7b, 0xd2, 0xf0, 0xa6,
	0x37, 0x22, 0xe8, 0x4c, 0xbb, 0xd8, 0xfc, 0x60, 0x39, 0xfc, 0x4b, 0x78, 0xe0, 0x31, 0x97, 0x1f,
	0x75, 0x07, 0x9c, 0x7f, 0xc8, 0x89, 0x0b, 0xf5, 0x0f, 0xff, 0x07, 0x00, 0x00, 0xff, 0xff, 0xe1,
	0xee, 0x30, 0xec, 0x6f, 0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TimeClient is the client API for Time service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TimeClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetResponse, error)
	SetMulti(ctx context.Context, in *SetMultiRequest, opts ...grpc.CallOption) (*SetMultiResponse, error)
	GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error)
	SetConfig(ctx context.Context, in *SetConfigRequest, opts ...grpc.CallOption) (*SetConfigResponse, error)
	SetConfigMulti(ctx context.Context, in *SetConfigMultiRequest, opts ...grpc.CallOption) (*SetConfigMultiResponse, error)
	GetDSTConfig(ctx context.Context, in *GetDSTConfigRequest, opts ...grpc.CallOption) (*GetDSTConfigResponse, error)
	SetDSTConfig(ctx context.Context, in *SetDSTConfigRequest, opts ...grpc.CallOption) (*SetDSTConfigResponse, error)
	SetDSTConfigMulti(ctx context.Context, in *SetDSTConfigMultiRequest, opts ...grpc.CallOption) (*SetDSTConfigMultiResponse, error)
}

type timeClient struct {
	cc *grpc.ClientConn
}

func NewTimeClient(cc *grpc.ClientConn) TimeClient {
	return &timeClient{cc}
}

func (c *timeClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/time.Time/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timeClient) Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetResponse, error) {
	out := new(SetResponse)
	err := c.cc.Invoke(ctx, "/time.Time/Set", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timeClient) SetMulti(ctx context.Context, in *SetMultiRequest, opts ...grpc.CallOption) (*SetMultiResponse, error) {
	out := new(SetMultiResponse)
	err := c.cc.Invoke(ctx, "/time.Time/SetMulti", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timeClient) GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error) {
	out := new(GetConfigResponse)
	err := c.cc.Invoke(ctx, "/time.Time/GetConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timeClient) SetConfig(ctx context.Context, in *SetConfigRequest, opts ...grpc.CallOption) (*SetConfigResponse, error) {
	out := new(SetConfigResponse)
	err := c.cc.Invoke(ctx, "/time.Time/SetConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timeClient) SetConfigMulti(ctx context.Context, in *SetConfigMultiRequest, opts ...grpc.CallOption) (*SetConfigMultiResponse, error) {
	out := new(SetConfigMultiResponse)
	err := c.cc.Invoke(ctx, "/time.Time/SetConfigMulti", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timeClient) GetDSTConfig(ctx context.Context, in *GetDSTConfigRequest, opts ...grpc.CallOption) (*GetDSTConfigResponse, error) {
	out := new(GetDSTConfigResponse)
	err := c.cc.Invoke(ctx, "/time.Time/GetDSTConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timeClient) SetDSTConfig(ctx context.Context, in *SetDSTConfigRequest, opts ...grpc.CallOption) (*SetDSTConfigResponse, error) {
	out := new(SetDSTConfigResponse)
	err := c.cc.Invoke(ctx, "/time.Time/SetDSTConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timeClient) SetDSTConfigMulti(ctx context.Context, in *SetDSTConfigMultiRequest, opts ...grpc.CallOption) (*SetDSTConfigMultiResponse, error) {
	out := new(SetDSTConfigMultiResponse)
	err := c.cc.Invoke(ctx, "/time.Time/SetDSTConfigMulti", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TimeServer is the server API for Time service.
type TimeServer interface {
	Get(context.Context, *GetRequest) (*GetResponse, error)
	Set(context.Context, *SetRequest) (*SetResponse, error)
	SetMulti(context.Context, *SetMultiRequest) (*SetMultiResponse, error)
	GetConfig(context.Context, *GetConfigRequest) (*GetConfigResponse, error)
	SetConfig(context.Context, *SetConfigRequest) (*SetConfigResponse, error)
	SetConfigMulti(context.Context, *SetConfigMultiRequest) (*SetConfigMultiResponse, error)
	GetDSTConfig(context.Context, *GetDSTConfigRequest) (*GetDSTConfigResponse, error)
	SetDSTConfig(context.Context, *SetDSTConfigRequest) (*SetDSTConfigResponse, error)
	SetDSTConfigMulti(context.Context, *SetDSTConfigMultiRequest) (*SetDSTConfigMultiResponse, error)
}

func RegisterTimeServer(s *grpc.Server, srv TimeServer) {
	s.RegisterService(&_Time_serviceDesc, srv)
}

func _Time_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/time.Time/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Time_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/time.Time/Set",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeServer).Set(ctx, req.(*SetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Time_SetMulti_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetMultiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeServer).SetMulti(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/time.Time/SetMulti",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeServer).SetMulti(ctx, req.(*SetMultiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Time_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/time.Time/GetConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeServer).GetConfig(ctx, req.(*GetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Time_SetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeServer).SetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/time.Time/SetConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeServer).SetConfig(ctx, req.(*SetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Time_SetConfigMulti_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetConfigMultiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeServer).SetConfigMulti(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/time.Time/SetConfigMulti",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeServer).SetConfigMulti(ctx, req.(*SetConfigMultiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Time_GetDSTConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDSTConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeServer).GetDSTConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/time.Time/GetDSTConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeServer).GetDSTConfig(ctx, req.(*GetDSTConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Time_SetDSTConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDSTConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeServer).SetDSTConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/time.Time/SetDSTConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeServer).SetDSTConfig(ctx, req.(*SetDSTConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Time_SetDSTConfigMulti_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDSTConfigMultiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimeServer).SetDSTConfigMulti(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/time.Time/SetDSTConfigMulti",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimeServer).SetDSTConfigMulti(ctx, req.(*SetDSTConfigMultiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Time_serviceDesc = grpc.ServiceDesc{
	ServiceName: "time.Time",
	HandlerType: (*TimeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Time_Get_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _Time_Set_Handler,
		},
		{
			MethodName: "SetMulti",
			Handler:    _Time_SetMulti_Handler,
		},
		{
			MethodName: "GetConfig",
			Handler:    _Time_GetConfig_Handler,
		},
		{
			MethodName: "SetConfig",
			Handler:    _Time_SetConfig_Handler,
		},
		{
			MethodName: "SetConfigMulti",
			Handler:    _Time_SetConfigMulti_Handler,
		},
		{
			MethodName: "GetDSTConfig",
			Handler:    _Time_GetDSTConfig_Handler,
		},
		{
			MethodName: "SetDSTConfig",
			Handler:    _Time_SetDSTConfig_Handler,
		},
		{
			MethodName: "SetDSTConfigMulti",
			Handler:    _Time_SetDSTConfigMulti_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "time.proto",
}
